README.md

Add a link to the Slack channel sign up URL.

Add Slack channel signup link

---

README.md

Fixed path to ingress-bad.yaml, as it was pointing to ~/opa/ingress-bad.yaml and not ./demo/ingress-bad.yaml

Fixed path to ingress-bad.yaml

---

deploy/delete-all.sh

deploy-all.sh script is expected to run from root. All path are set accordingly in this script.
On the similar ground from delete-all.sh script should run from root too and the opa.yaml path is adjusted to make it consistent.
Also delete-all.sh now removes "secret" directory too, making it clean delete on local.

Fix delete all script

---

pkg/webhook/policy.go

- Add `--port` flag: port for the server. defaulted to 443 if unspecified
- Add `--webhook-name` flag: domain name of the webhook, with at least three segments separated by dots. defaulted to mutation.styra.com if unspecified
cc @maxsmythe @rite2nikhil

make port and webhook domain name customizable

---

cmd/manager/main.go
pkg/audit/controller.go
pkg/audit/manager.go

This adds the audit feature for gatekeeper. 
Note:
- `message` is currently truncated at 256. 
- flag `--auditInterval` is the interval to run audit in seconds. defaulted to 60 secs if unspecified.
- flag `--constraintViolationsLimit` is the limit of number of violations per constraint. defaulted to 20 violations if unspecified.
- audit violations are added to each failed constraint's status field:
```yaml
status:
auditTimestamp: 2019-04-11T07:24:44Z
enforced: true
violations:
- kind: Namespace
message: 'you must provide labels: {"gatekeeper"}'
name: kube-public
```
- will add test as a followup PR. wanted to get feedback on this first.
Sample output:
```yaml
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: K8sRequiredLabel
metadata:
annotations: …
```

Add audit feature

---

Makefile

For cutting our first release after the constraint framework integration, per weekly meeting on April 16, 2019.

Bump version to 3.0.0

---

pkg/webhook/policy.go

Do not allow gatekeeper to self-manage

---

pkg/webhook/policy.go

Currently we are relying on the framework to set status codes, which always returns 200 OK, which is not okay in some situations.
This fixes a bug where rejected create requests appear to apply successfully and cause kubectl to return an exit code of zero.

Return appropriate status codes for rejected requests

---

deploy/gatekeeper-constraint.yaml

Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
Running through the https://github.com/open-policy-agent/gatekeeper#deploying-a-release-using-prebuilt-image yields the following error:
```sh
$ kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/deploy/gatekeeper-constraint.yaml
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding created
clusterrole.rbac.authorization.k8s.io/manager-role created
validatingwebhookconfiguration.admissionregistration.k8s.io/validating-webhook-configuration created
customresourcedefinition.apiextensions.k8s.io/constrainttemplates.templates.gatekeeper.sh created
customresourcedefinition.apiextensions.k8s.io/configs.config.gatekeeper.sh created
Error from server (NotFound): error when creating …
```

Add namespace spec to deployment template

---

demo/agilebank/demo.sh
pkg/watch/manager.go
pkg/watch/manager_test.go

Another `wm.started` check needed so that watch manager can eventually restart. Gets stuck in a stopped state forever otherwise.
Signed-off-by: Craig Tabita <ctab@google.com>

add second check if watchmanager started

---

deploy/gatekeeper.yaml

validating webhook config currently excludes namespace with `control-plane` label
```yaml
namespaceSelector:
matchExpressions:
- key: control-plane
operator: DoesNotExist
```

add control-plane label to exclude gk ns

---

pkg/webhook/policy.go

Fixes #144 
NOTE: 
- I did not add `admissionregistrationv1beta1.DELETE` to the validation webhook config by default. Users can do that manually after it is deployed. Do we need a flag to enable DELETE by default as part of the initial deployment?

Fix support for DELETE

---

Gopkg.lock
README.md
demo/agilebank/remediation/k8sbannedimagetags_template.yaml
demo/agilebank/templates/k8sallowedrepos_template.yaml
demo/agilebank/templates/k8scontainterlimits_template.yaml
demo/agilebank/templates/k8srequiredlabels_template.yaml
demo/agilebank/templates/k8suniqueserviceselector_template.yaml
demo/basic/bad/bad_template.yaml
demo/basic/templates/k8srequiredlabels_template.yaml
demo/basic/templates/k8srequiredlabels_template_external_data.yaml
demo/basic/templates/k8suniquelabel_template.yaml
demo/basic/templates/k8suniquelabels_template.yaml
example/templates/k8srequiredlabels_template.yaml
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go
vendor/github.com/open-policy-agent/frameworks/constraint/README.md
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/client.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/client_test.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/drivers/local/local_test.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/e2e_tests.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/regolib/src.go

We should push a release after merging this PR to make sure demo/example
still work.

 Rename deny rule to violation

---

pkg/audit/manager.go

@timothyhinrichs @maxsmythe 
Per our discussion for the [Dry Run design proposal](https://docs.google.com/document/d/17nJDJxjY_XHV8zrMNdOi2hFgfm6XKGJi0QyznsbhQ70/edit?usp=sharing), this PR updates the status field of Constraint object to include the `enforcementAction` the violation resulted from.
Example of a Constraint's status field as a result of this PR:
```yaml
status:
auditTimestamp: "2019-07-10T06:06:29Z"
byPod:
- enforced: true
id: gatekeeper-controller-manager-0
violations:
- enforcementAction: deny
kind: Pod
message: 'you must provide labels: {"gatekeeper"}'
name: nginx-4rfps
namespace: test
- enforcementAction: deny
kind: Pod
message: 'you must provide labels: {"gatekeeper"}'
name: nginx-xrxjk
namespace: test
```
Once we have …

Add enforcementAction to status

---

config/rbac/rbac_role.yaml
pkg/controller/add_mutationtemplate.go
pkg/controller/mutationtemplate/mutationtemplate_controller.go
pkg/controller/mutationtemplate/mutationtemplate_controller_suite_test.go
pkg/controller/mutationtemplate/mutationtemplate_controller_test.go

Files created with kubebuilder and make to create a MutationTemplate controller skeleton/base similar to the ConstraintTemplate controller. Should compile fine, not sure if the RBAC (`rbac_role.yaml`) is necessary or not.

Kubebuilder files for a MutationTemplate controller

---

Gopkg.lock
pkg/controller/add_mutationtemplate.go
pkg/controller/mutationtemplate/mutationtemplate_controller.go
pkg/controller/mutationtemplate/mutationtemplate_controller_test.go
vendor/github.com/open-policy-agent/frameworks/constraint/config/crds/templates_v1alpha1_mutationtemplate.yaml
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1alpha1/mutationtemplate_types.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1alpha1/mutationtemplate_types_test.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/client.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/crd_helpers.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/crd_helpers_test.go

The mutation template controller now initializes an opa client similar to the constraint template controller so that it can can call createMutationCRD when Reconciling incoming MutationTemplates (currently assumes that all Templates are being newly created - doesn't handle updates or deletes yet).
Tested using `make test` as well as installing & deploying GK to my personal GKE cluster, then watching for object printouts in the container logs.

Mutation Template Controller now includes an OPA Client, handles the creation of Mutation CRDs

---

pkg/controller/constrainttemplate/constrainttemplate_controller.go

Conversion errors should be fatal

---

pkg/controller/mutationtemplate/mutationtemplate_controller.go
pkg/controller/mutationtemplate/mutationtemplate_controller_suite_test.go

When a MutationTemplate CR is deleted from K8s, it will now
delete its associated MutationCRD (and any Mutation CRs underneath it)
before deleting the Template CR. MutationCRD creation now includes the
application of a finalizer to achieve this additional cleanup logic.
Tested to see if it compiles with `make test`. To test the actual deletion, I ran some commands in my own GKE cluster:  `kubectl apply -f mutationtemplate.yaml` (a generic MutationTemplate yaml file),  `kubectl get crds` to see the template's associated CRD had been created (e.g. `testmutation.mutation.gatekeeper.sh`), then `kubectl delete -f mutationtemplate.yaml`. Upon inspecting the CRDs again with `kubectl get crds`, `testmutation...sh` should have also been deleted along with the template.

 MT Controller handles deletion of MutationTemplates + Mutation CRDs 

---

.travis.yml
Makefile
README.md
docs/RELEASE.md

- Update RELEASE doc
- Add e2e after a new tag is released
A sample build when we push a tag: https://travis-ci.org/open-policy-agent/gatekeeper/builds/583049644

Add verify release stage to CI

---

Dockerfile
Dockerfile_ci
config/manager/manager.yaml
deploy/gatekeeper.yaml

**Changes:**
- Update base packages in the docker image build for vulnerability patches
- Configure image to run with a non-root UID so the deployment no longer needs to run privileged
- Update deployment files with listening port override to 8443

Image package update and run as a non-root user

---

library/general/uniqueingresshost/constraint.yaml
library/general/uniqueingresshost/example.yaml
library/general/uniqueingresshost/example1.yaml
library/general/uniqueingresshost/example2.yaml
library/general/uniqueingresshost/src.rego
library/general/uniqueingresshost/src_test.rego
library/general/uniqueingresshost/sync.yaml
library/general/uniqueingresshost/template.yaml

Add unique ingress host to library

---

pkg/watch/manager.go

This will fix cases where constraints fail to be enforced and/or finalizers fail to be removed when there is a watch on a non-existent group and the resource expected to be enforced/cleaned-up are not currently watched.

Watch manager should ignore unrecognized groups

---

.travis.yml
Makefile

- Updates k8s node image to v.1.16.3
- removed deprecated `kind get kubeconfig-path`

Update kind to v0.6.0

---

config/manager/manager.yaml
deploy/gatekeeper.yaml
deploy/gatekeeper_kubebuilder_v2.yaml

increase cpu limits

---

pkg/controller/constraint/constraint_controller.go

Signed-off-by: Emma McMillan <emma.mcmillan@microsoft.com>
Fixes #272

Stop caching constraint status to OPA

---

docs/design/README.md

I thought it'd be a good idea to start indexing design documents in
a central location.
I've included all the design docs I'm aware of/could find in my
history. Apologies if I've missed any.

Add index of design documents

---

Makefile
README.md
config/manager/manager.yaml
deploy/deprecated_kubebuilder_v1_gatekeeper.yaml
deploy/gatekeeper.yaml

This moves the original gatekeeper.yaml manifest to deprecated_kubebuilder_v1_gatekeeper.yaml

Bump deployment v3.1.0-beta.0

---

Makefile
config/manager/manager.yaml
deploy/gatekeeper.yaml

Add security context to Gatekeeper container

---

library/general/allowedrepos/template.yaml
library/general/containerlimits/template.yaml
library/general/httpsonly/template.yaml
library/general/requiredlabels/template.yaml
library/general/uniqueingresshost/template.yaml
library/general/uniqueserviceselector/template.yaml
library/pod-security-policy/allow-privilege-escalation/template.yaml
library/pod-security-policy/apparmor/template.yaml
library/pod-security-policy/flexvolume-drivers/template.yaml
library/pod-security-policy/forbidden-sysctls/template.yaml
library/pod-security-policy/fsgroup/template.yaml
library/pod-security-policy/host-filesystem/template.yaml
library/pod-security-policy/host-namespaces/template.yaml
library/pod-security-policy/host-network-ports/template.yaml
library/pod-security-policy/privileged-containers/template.yaml
library/pod-security-policy/proc-mount/template.yaml
library/pod-security-policy/read-only-root-filesystem/template.yaml
library/pod-security-policy/seccomp/template.yaml
library/pod-security-policy/selinux/template.yaml
library/pod-security-policy/users/template.yaml
library/pod-security-policy/volumes/template.yaml

From https://github.com/open-policy-agent/gatekeeper/issues/170, I understand that only name is required.
As it stands, I'm getting a new generation for each template every time I run `kubectl apply` (which I run regularly as part of my CD):
```
-  generation: 250
+  generation: 251
name: k8srequiredlabels
resourceVersion: "102333523"
selfLink: /apis/templates.gatekeeper.sh/v1beta1/constrainttemplates/k8srequiredlabels
@@ -17,6 +17,9 @@
spec:
names:
kind: K8sRequiredLabels
+        listKind: K8sRequiredLabelsList
+        plural: k8srequiredlabels
+        singular: k8srequiredlabels
validation:
openAPIV3Schema:
properties:
```

library: remove all spec.crd.spec.names except kind

---

library/general/allowedrepos/kustomization.yaml
library/general/containerlimits/kustomization.yaml
library/general/httpsonly/kustomization.yaml
library/general/kustomization.yaml
library/general/requiredlabels/kustomization.yaml
library/general/uniqueingresshost/kustomization.yaml
library/general/uniqueserviceselector/kustomization.yaml
library/kustomization.yaml
library/pod-security-policy/allow-privilege-escalation/kustomization.yaml
library/pod-security-policy/apparmor/kustomization.yaml
library/pod-security-policy/flexvolume-drivers/kustomization.yaml
library/pod-security-policy/forbidden-sysctls/kustomization.yaml
library/pod-security-policy/fsgroup/kustomization.yaml
library/pod-security-policy/host-filesystem/kustomization.yaml
library/pod-security-policy/host-namespaces/kustomization.yaml
library/pod-security-policy/host-network-ports/kustomization.yaml
library/pod-security-policy/kustomization.yaml
library/pod-security-policy/privileged-containers/kustomization.yaml
library/pod-security-policy/proc-mount/kustomization.yaml
library/pod-security-policy/read-only-root-filesystem/kustomization.yaml
library/pod-security-policy/seccomp/kustomization.yaml
library/pod-security-policy/selinux/kustomization.yaml
library/pod-security-policy/users/kustomization.yaml
library/pod-security-policy/volumes/kustomization.yaml

Add `kustomization.yaml` files for the entire library, the general/pod-security-policy libraries and the individual templates. This allows you to reference the library as a whole, only the templates
you're interested in or pull in templates from different tags.

kustomize the template library

---

main.go
pkg/controller/config/config_controller_test.go
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go
pkg/watch/manager.go
pkg/watch/manager_test.go
pkg/watch/registrar.go

Clean up watch manager

---

pkg/webhook/certs.go

Use namespace of Pod as namespace for cert secret

---

pkg/audit/manager.go

I saw a ton of `"logger":"controller","msg":"updating constraint"` in our logs an was worried that something is constantly changing the constraints ... turns out it is just the status update, so say that it is only changing the status.

say that the status is changed, not the contraint itself

---

chart/gatekeeper-operator/generate_helm_template.sh
chart/gatekeeper-operator/helm-modifications/helm-modifications.yaml
chart/gatekeeper-operator/templates/gatekeeper.yaml
chart/gatekeeper-operator/values.yaml

The resources were incorrectly applied to the deployment rather than the
containers. This moves the resources to the containers and allows users
to change the values from the values.yaml file.

Move resources field to values.yaml

---

README.md

Cleaning up the installation instructions. Mainly, making it so you only have to enter the docker image location once.
Signed-off-by: Craig Tabita <ctab@google.com>

cleanup readme installation instructions

---

README.md

`make deploy` has `make patch-image` as a dependency so the deploy without a repository value was overwriting the image value in `manager_image_patch.yaml` with the default. 
Fixing this by removing the standalone `make patch-image` and specifying a repository in `make deploy`.
Plus, more README cleanup
Signed-off-by: Craig Tabita <ctab@google.com>

Fix patch-image overwrite issue + more installation readme cleanup

---

main.go

Disable kubebuilder metrics by default as they don't
play well with the watch manager. Currently it's possible
for stale metrics to persist after restart. In addition, because
metric names correlate with template names, this means
that the installed constraint templates would be visible
if these metrics were enabled.
Default metrics can still be enabled by setting:
`--metrics-addr=":8080"`

Disable default Kubebuilder metrics

---

chart/gatekeeper-operator/templates/gatekeeper.yaml
config/manager/manager.yaml
deploy/gatekeeper.yaml
go.mod
go.sum
main.go

Health and ready checks

---

README.md
pkg/target/regolib/src.rego
pkg/target/target.go
pkg/target/target_integration_test.go
pkg/target/target_template_source.go

This adds excludedNamespaces to the MatchSchema and provides the logic for checking it.
If there is anything that needs to be added or changed let me know :)

Add excludedNamespaces match type

---

main.go

Fixes #452 
Seems by removing the sleep in main.go in #418 the pod to exit before it has a chance to generate the cert. 

Fixes crashloop caused by cert gen

---

pkg/webhook/policy.go

It's a simple change to allow the Config > validation > traces > user [] > dump to be case insensitive.
I was writing the config file without copying/pasting from examples and mistakenly used "all". Ended spending quite some time to figure it out the issue.
I would even suggest changing the variable to bool instead of string. Happy to amend the PR if you prefer.

make tracing dump case insensitive

---

pkg/controller/sync/sync_controller.go
pkg/logging/logging.go

syncing happens a lot, especially when watching many resources and the constant "data will be added"
spam is only needed when "debugging" sync issues, so change to debug
fixes https://github.com/open-policy-agent/gatekeeper/issues/399
@maxsmythe

change 'data will be added' from Info to Debug to be less spammy

---

README.md

Adding troubleshoot information refer to running Gatekeeper on GKE private nodes due to known issue of master plane only able to communicate with webhook on port 443.
Fix #498 .

update README-  GKE private node webhook exceptions

---

.golangci.yaml

Removing  `unused` for now until we move off travis. Ref: https://github.com/golangci/golangci-lint/issues/337#issuecomment-536721714

Fix golangci-lint memory usage

---

pkg/audit/manager.go

Return error when negative values are passed in for `audit-interval` or `constraint-violations-limit`

Fix negative values for audit

---

pkg/controller/config/config_controller.go

Generally speaking, now that we have the status endpoint on everything, we should avoid writing using the regular client anyway.

Remove unnecessary config writes

---

pkg/audit/manager.go

Fixes #476
When we changed to status client, it also changed `GetSelfLink()` to return with `/status` suffix (which is status subresource's selflink value), it didn't match with the existing `ucloop.uc` key value

fix max retries error

---

README.md
SECURITY.md

This follows the convention in OPA (and other CNCF projects) around security release processes.
Signed-off-by: Torin Sandall <torinsandall@gmail.com>

docs: Update README with security release process pointer

---

library/pod-security-policy/forbidden-sysctls/src.rego
library/pod-security-policy/forbidden-sysctls/src_test.rego
library/pod-security-policy/forbidden-sysctls/template.yaml

The Pod will be blocked if `forbiddenSysctls` is a wildcard and the sysctls list in the Pod is empty. The change adds quick check to see if any sysctls are set to the Pod.

Fix PSP sysctls rego

---

pkg/webhook/certs.go

Since the controller manager will no longer restart when certRotator
returns, the return after a cert rotation in certRotator.Start() makes
certRotator stop working after first cert rotation is done before the
stop channel closes.
This commit keeps the certRotator blocked and rotating certs
periodically until the stop channel is closed. There's no need to
trigger a restart for webhooks to pick up the new certs because
CertWatcher can renew the webhook certs on the fly.
Tested on a GKE cluster:
I set rotationCheckFrequency to 1 minute, certValidityDuration to 10
minutes and lookaheadTime() to 6 minutes to test the behaviour of a cert
rotation and how webhooks react.
There would always be 1 manager restart as expected since the webhook
couldn't find the cert files in the first start.
I also …

Fix certRotator early return bug

---

Makefile
config/manager/manager.yaml
manifest_staging/chart/gatekeeper-operator/generate_helm_template.sh
manifest_staging/chart/gatekeeper-operator/helm-modifications/helm-modifications.yaml
manifest_staging/chart/gatekeeper-operator/templates/gatekeeper.yaml
manifest_staging/deploy/gatekeeper.yaml

Audit should still be run as a deployment so that we can control update behavior if necessary and get whatever other app management features come with deployments in the future.

Run audit in a deployment

---

pkg/webhook/certs.go
pkg/webhook/certs_test.go
pkg/webhook/policy.go

Add new fields in CertRotator and ReconcileVWH structs to store previous
"Gatekeeper" constants and get rid of referencing global constants in the
code.
Refactor AddRotator() to take CertRotator and vwhName as parameters.
Pass all "Gatekeeper" constants from the caller instead.
Tested on a GKE cluster with "make test-e2e".

Refactor cert.go for easy reuse

---

demo/agilebank/templates/k8scontainterlimits_template.yaml
library/general/containerlimits/src.rego
library/general/containerlimits/src_test.rego
library/general/containerlimits/template.yaml
library/general/containerresourceratios/src.rego
library/general/containerresourceratios/src_test.rego
library/general/containerresourceratios/template.yaml
test/bats/tests/templates/k8scontainterlimits_template.yaml

It's possible for memory resources to be represented with the `m` unit. This causes problems for the examples listed in this repo which parse memory, since they are unaware of how to convert from this unit.
For example creating the following deployment results in pods with a resource limit and request of `1288490188800m`.
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
name: foobar
labels:
app: nginx
spec:
replicas: 3
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- name: nginx
image: nginx:1.14.2
ports:
- containerPort: 80
resources:
limits:
cpu: "1"
memory: 1.2Gi
requests:
cpu: "10m"
memory: 1.2Gi
```

Allow for 'm' memory unit in examples

---

Makefile

This avoids issues like infinitely appending fields
to manager_image_patch.yaml and people's build files
failing due to an outdated patch.

Always recreate manager_image_patch.yaml

---

pkg/controller/sync/sync_controller.go
pkg/logging/logging.go

Lower the verbosity of the ReconcileSync logging (to avoid logging sensitive information).
https://github.com/open-policy-agent/gatekeeper/issues/574

Decrease verbosity of ReconcileSync logging

---

library/pod-security-policy/apparmor/src.rego
library/pod-security-policy/apparmor/src_test.rego
library/pod-security-policy/apparmor/template.yaml

Fixes an issue with the AppArmor rego.
A pod was considered valid if only one container had a valid AppArmor profile and other containers did not. Now each container is considered separately.

Ensure AppArmor rego throws violations as expected

---

main.go
pkg/webhook/certs.go
pkg/webhook/certs_test.go
pkg/webhook/policy.go

Make controller manager start only with the cert generation controllers
if cert rotation is not disabled (by "disable-cert-rotation" flag) and
the webhook is enabled. All other controllers will be added to the
manager on the fly if cert generation is disabled or the cert files are
ready. The webhook will be added then too.
Make 'CertRotator' more robust from cert rotation contention among
multiple pods.
Tested on a GKE cluster. Passed "make test-e2e".
Fixes #465

Sync cert generation before starting webhooks

---

demo/agilebank/templates/k8scontainterlimits_template.yaml
library/general/containerlimits/src.rego
library/general/containerlimits/src_test.rego
library/general/containerlimits/template.yaml
library/general/containerresourceratios/src.rego
library/general/containerresourceratios/src_test.rego
library/general/containerresourceratios/template.yaml
test/bats/tests/templates/k8scontainterlimits_template.yaml

Lowercase k should be the unit of memory used in the examples instead of uppercase.
https://github.com/kubernetes/apimachinery/blob/37516730658b375821d581544103caaca05ada05/pkg/api/resource/quantity.go#L46
https://github.com/open-policy-agent/gatekeeper/issues/583

Use "k" instead of "K" for mem parsing

---

library/pod-security-policy/seccomp/src.rego
library/pod-security-policy/seccomp/src_test.rego
library/pod-security-policy/seccomp/template.yaml

Signed-off-by: Emma McMillan <emma.mcmillan@microsoft.com>
This fix updates the seccomp pod-security-policy to respect the container-level seccomp flag, and to raise a violation per container in error.
The existing rego will match all containers as passing if at least one container is valid. It also respects the pod-level flag over the container-level flag. As k8s will give the container-level flag precedence, this change ensures the rego matches that, and ensures each container in violation is flagged.

Update Seccomp PSP to respect container level flag

---

pkg/webhook/policy.go
pkg/webhook/policy_test.go
test/client/noop_client.go

Fixes a problem where the created namespace is not found by cached client when a admission request is being reviewed. This can happen if admission request is made immediately after the namespace is created.
Fixes #558 

Fix cold cache problem by making a request to api-server

---

pkg/webhook/policy.go

On a CREATE operation, the client may omit name and rely on the server to generate the name. For this case, we get the resource name from the object metadata.
Fixes #617
Was able to repro the issue on k8s v1.15.4. Verified the fix works there and v1.16.1.

Fix empty resource name for logDenies

---

config/manager/manager.yaml
manifest_staging/charts/gatekeeper/values.yaml
manifest_staging/deploy/gatekeeper.yaml

Since we are only supporting Linux OS right now, adding a nodeSelector to assign deploments to Linux agents

NodeSelector for Linux

---

Makefile

we were not pushing latest dev tag (only the commit sha tags)

push dev tag

---

.github/workflows/workflow.yaml

Ignoring CI for docs, library, demo, example, deprecated and markdown files which doesn't get tested currently

Ignore CI for certain paths

---

pkg/webhook/policy.go

Adds the user name of the request that is being denied, helps during log reviews to identify users.

Log the username originating the request that is being denied

---

pkg/readiness/object_tracker.go
pkg/readiness/object_tracker_test.go

Resources which are being terminated on startup (which gatekeeper is trying to sync/reconcile) cause gatekeeper to fail its readiness check indefinitely.
To help with this let's not look for resources marked for termination in the readiness check.
Fixes #660
The readiness check still seems a little shaky though. As @maxsmythe pointed out in the issue, there's still the possibility that a resource can be deleted between when the `ready_tracker` discovers the resource, and when the controllers start reconciling.

Ensure terminated are ignored for readiness

---

Makefile
README.md

- update readme with `make docker-buildx` instructions
- setting or exporting `DOCKER_CLI_EXPERIMENTAL` at the top doesn't work
Fixes #666

update readme with buildx instructions

---

config/crd/bases/config.gatekeeper.sh_configs.yaml
config/crd/bases/status.gatekeeper.sh_constraintpodstatuses.yaml
config/crd/bases/status.gatekeeper.sh_constrainttemplatepodstatuses.yaml
config/rbac/role.yaml
manifest_staging/charts/gatekeeper/templates/config-customresourcedefinition.yaml
manifest_staging/charts/gatekeeper/templates/constraintpodstatus-customresourcedefinition.yaml
manifest_staging/charts/gatekeeper/templates/constrainttemplatepodstatus-customresourcedefinition.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-manager-role-clusterrole.yaml
manifest_staging/deploy/gatekeeper.yaml
pkg/controller/constrainttemplate/constrainttemplate_controller.go

This adds a kubebuilder marker for ConstraintTemplates to generate the
necessary RBAC permissions for the gatekeeper-manager-role ClusterRole
to access the ConstraintTemplate finalizer subresource. This is needed
in order to set an owner reference on the CRD being created by the
ConstraintTemplate.
Fixes #603

Add kubebuilder RBAC marker for ConstraintTemplate

---

pkg/audit/manager.go

Fixes string conversion for total violations for `constraint_audited` event type

Fix total violations count in logs

---

pkg/webhook/namespacelabel.go
pkg/webhook/policy.go

This mitigates the hard-down webhook bug cited in #661
This should be a temporary mitigation, as it doesn't fix the full race condition. Now the controller-runtime webhook logs will be tagged with semi-random names.

Mitigate race condition setting logger on webhook initialization

---

Makefile
docs/RELEASE.md

Currently, every time a new release is made, the base url points to master. This means when you pull the chart index regardless of a commit, it will not find the correct version. Instead the index should be specified correctly in the version.

set base helm chart url correctly to the release version

---

README.md
pkg/target/regolib/namespace_selector_test.rego
pkg/target/regolib/scope_selector_test.rego
pkg/target/regolib/src.rego
pkg/target/target.go
pkg/target/target_integration_test.go
pkg/target/target_template_source.go
pkg/target/target_test.go

Signed-off-by: Robert Sheehy <rob.sheehy@workiva.com>
This change helps ensure gatekeeper includes cluster scoped resources when using any of the namespace filtering (since this is closer to how Kubernetes handles matching).
For example this is how Kubernetes handles the `namespaceSelector` on Webhooks.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#mutatingwebhook-v1beta1-admissionregistration-k8s-io
> NamespaceSelector decides whether to run the webhook on an object based on whether the namespace for that object matches the selector. If the object itself is a namespace, the matching is performed on object.metadata.labels. If the object is another cluster scoped resource, it never skips the webhook.
* Add `scope` to the …

Ensure cluster scoped resources always match namespace filters

---

library/pod-security-policy/forbidden-sysctls/src.rego
library/pod-security-policy/forbidden-sysctls/src_test.rego
library/pod-security-policy/forbidden-sysctls/template.yaml

Signed-off-by: Emma McMillan <emma.mcmillan@microsoft.com>
The current implementation of the Forbidden Sysctls PSP will emit one message for any number of violations on a pod. This update brings the rego in line with other PSPs and emits a separate violation for each sysctl in error.

Update Forbidden Sysctls PSP with separate message for each violation

---

library/pod-security-policy/volumes/src.rego
library/pod-security-policy/volumes/src_test.rego
library/pod-security-policy/volumes/template.yaml

The current implementation of the Volumes PSP will emit one message for any number of violations on a pod. This update brings the rego in line with other PSPs and emits a separate violation for each volume in error.

Update Volumes PSP with a separate message for each violation.

---

pkg/audit/manager.go

returns early from audit operation if there are no constraints in the cluster

return early from audit if there are no constraints

---

Makefile
cmd/build/helmify/kustomize-for-helm.yaml
cmd/build/helmify/static/README.md
cmd/build/helmify/static/values.yaml
config/crd/bases/config.gatekeeper.sh_configs.yaml
config/manager/manager.yaml
manifest_staging/charts/gatekeeper/README.md
manifest_staging/charts/gatekeeper/templates/config-customresourcedefinition.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/charts/gatekeeper/values.yaml
manifest_staging/deploy/gatekeeper.yaml
pkg/audit/manager.go
pkg/webhook/policy.go
test/bats/test.bats

Fixes #579 
Sample event outputs for reasons `FailedAdmission`, `DryrunViolation`, and `AuditViolation` respectively:
```sh
kubectl get event -n gatekeeper-system                                                                                                                                
LAST SEEN   TYPE      REASON              OBJECT                                   MESSAGE
53m         Warning   FailedAdmission   pod/opa-test-deployment-566fc979b4-zxkrm   Admission webhook "validation.gatekeeper.sh" denied request, Resource Namespace: default, …
```

Add support for emit k8s events for audit

---

pkg/controller/constraint/constraint_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/controller.go

This PR should avoid triggering a watch of all pods in the cluster when getting the self-referenced pod.
This also re-adds the ability to run Gatekeeper outside of a Kubernetes cluster for testing purposes, per #738 
Fixes #742 

Do not trigger a watch of pods for status owner ref

---

pkg/audit/manager.go

Adds an opt-in flag to use the match kinds specified by constraints to optimize audit duration. If any constraints does not define this field, it will be same as not having this flag turned off and will check all the resources in the cluster.
Audit times are on a 50 node cluster with 5k pods/serviceaccounts/namespaces with 30 templates (1 constraints each - using `dryrun` enforcement action) and violations limit is set as 0.
without this optimization:
- `constraint-match-kind-only: false` and `emit-audit-events: false`: audit took ~20 minutes
- `constraint-match-kind-only: false` and `emit-audit-events: true`: audit took ~40 minutes
with this optimization, and only `Pod` kind defined in the …

Use constraint match kind on audit

---

pkg/webhook/policy.go

Cherry-pick #793 into the `release-3.1` branch for inclusion in the next point release.
**Which issue(s) this PR fixes:**
This makes sure server-side apply requests of Namespaces look like non-server-side apply requests to avoid breaking any code that detects cluster-scoped objects by checking for req.namespace == ""

Cherry pick #793 - Fix server-side apply checks of namespaces

---

pkg/webhook/certs.go

Go 1.15 [deprecated the use of the CommonName field as a HostName when no SANs are present](https://golang.org/doc/go1.15#commonname).
Kubernetes v1.19 is [now built with 1.15](https://github.com/kubernetes/kubernetes/blob/release-1.19/build/build-image/cross/VERSION) and so has this deprecation in place.
Thus the default installation on a 1.19 cluster will have webhook TLS errors. e.g., when running the `agilebank` demo:
```
$ kubectl create ns advanced-transaction-system
Error from server (InternalError): Internal error occurred: failed calling webhook "check-ignore-label.gatekeeper.sh": Post "https://gatekeeper-webhook-service.gatekeeper.svc:443/v1/admitlabel?timeout=5s": x509: certificate relies on legacy Common Name field, use SANs or …
```

add DNSName to SAN for go1.15 CN deprecation

---

Makefile

**What this PR does / why we need it**: 
Updates the KIND invocation to accept a k8s version, and defaults to the latest published stable version.
**Which issue(s) this PR fixes** : N/A
**Special notes for your reviewer**: Last follow up to https://github.com/open-policy-agent/gatekeeper/pull/811#issuecomment-686850836! :slightly_smiling_face:

Make e2e k8s version configurable

---

example/templates/k8srequiredlabels_template.yaml

Fixes the example template. The items field of properties is a JSONSchemaPropsOrArray and not a string.
To give a consistent and bug free example. Plus, it was found while investigating an issue.
Fixes #832

Fix the example template.

---

README.md

Gatekeeper does not work out of the box on OpenShift, because of the different
security constructs. Here we suggest the changes required to make it work.
Fixes #790

Add a section about running gatekeeper on OCP.

---

charts/gatekeeper/templates/constrainttemplate-customresourcedefinition.yaml
cmd/build/helmify/kustomize-for-helm.yaml

The current shortname (constraints) is misleading as constraint (singular) is used to refer generated CRDs.
Fixes #677 (the first bit)

Remove the shortname from the constraint template.

---

test/bats/test.bats
test/bats/tests/bad/ignore_label_ns.yaml

This step is expected to fail. It was failing because of file was not found. However, we want it to fail with a deny because of admission flag can only be added when a namespace is added to `--exempt-namespace`. 
- Added a specific string assert match to confirm it is getting denied by Gatekeeper.
- updated `yes` to `"yes"` because of k8s string validation.
Fixes #872 

Fix path in ignore label test

---

config/webhook/webhook_patch.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
manifest_staging/deploy/gatekeeper.yaml

This fixes an issue where certain core K8s leader elections can time out if Gatekeeper's webhook is down, preventing self-healing.
Fixes #870 

Reduce webhook timeout to 3 seconds

---

.github/workflows/workflow.yaml

- GitHub deprecated `add-path` command. Changing it to the new way.
```
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
- Remove unnecessary `setup-go` since we build in containers, and added `setup-go` in unit test which calls `go test` natively
Fixes #

Fix deprecated add-path in CI

---

Dockerfile

Broken build: https://github.com/open-policy-agent/gatekeeper/runs/1223178572?check_suite_focus=true
Distroless added support for `arm64` which changed `nonroot` tag from a manifest to a manifest list (that includes `amd64` and `arm64` but not `arm/v7`)
https://github.com/GoogleContainerTools/distroless/issues/377#issuecomment-701046893
Reverting to old behavior by specifying `nonroot-amd64` tag which is a manifest
Fixes #

Fix arm/v7 builds

---

README.md

We are giving the false impression that constraint template authors need to provide names other than `kind`, we should fix that.

Remove unnecessary name fields from template example in readme

---

README.md

Currently `master` is pointing to `v3.1.0-rc.1` until we do a new release.
This is a quick fix so new users don't get broken due to k8s v1.19 cert change.
We should discuss versioning installation instead of pulling from master.
Fixes #

update readme to v3.1.1 release

---

pkg/audit/manager.go

- When there are multiple templates with multiple constraints, `ucloop` is not `nil` anymore in the second run, and it closes the channel on the previously running thread before it fully finishes iterating through all the constraints. When this happens, constraint resource doesn't get updated (logs will still have correct number of  violations).
- Passing logger to `ucloop` to be able to debug using `audit_id`.
Fixes #

Fix audit cancelling previously running thread

---

Makefile
build/tooling/Dockerfile
config/crd/bases/config.gatekeeper.sh_configs.yaml
config/crd/bases/mutations.gatekeeper.sh_assign.yaml
config/crd/bases/mutations.gatekeeper.sh_assignmetadata.yaml
config/crd/bases/status.gatekeeper.sh_constraintpodstatuses.yaml
config/crd/bases/status.gatekeeper.sh_constrainttemplatepodstatuses.yaml
manifest_staging/charts/gatekeeper/crds/config-customresourcedefinition.yaml
manifest_staging/charts/gatekeeper/crds/constraintpodstatus-customresourcedefinition.yaml
manifest_staging/charts/gatekeeper/crds/constrainttemplate-customresourcedefinition.yaml
manifest_staging/charts/gatekeeper/crds/constrainttemplatepodstatus-customresourcedefinition.yaml
manifest_staging/deploy/gatekeeper.yaml

The `make manifests` target currently relies on the developer having the correct version (`0.3.0`) of the `controller-gen` CLI tool.  This broke for me, as I had the old `2.5.0` installed.
By wrapping a docker container around `controller-gen`, I've locked this call to a specific version of the tool.  A gatekeeper developer need not even install this tool on their system, as long as they have `docker`.
This will also allow us to upgrade this library in the future with zero coordination among gatekeeper developers.

dockerize controller-gen

---

build/tooling/Dockerfile

The call to `make generate` requires CGO support inside the docker
image.  The golang:1.15-alpine image does not include this support, and
this change adds a RUN command that installs the necessary libraries.

Fix broken `make generate`, which requires CGO

---

config/overlays/mutation/kustomization.yaml

Typo in file name
The related file is here:
https://github.com/open-policy-agent/gatekeeper/blob/f3ec64a56154cd991e98387329083d243c967879/config/crd/bases/mutations.gatekeeper.sh_assign.yaml

Fix typo in mutation kustomize

---

config/manager/manager.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/deploy/gatekeeper.yaml

Adds `automountServiceAccountToken: true` within the `PodSpec` of each of the `Deployments`.  
Terraform defaults this field to `false` as the average bespoke service deployed to k8s does not need to access the API server, and thus shouldn't have a service account token mounted to the pod(s).  As gatekeeper pods _do_ talk to the API server, we need this field set to `true`.  
`automountServiceAccountToken: true` is the default value for a Pod, so non-terraform users will see no change in behavior.
fixes #922

Specify automountServiceAccountToken: true on Deployments

---

README.md

After https://github.com/open-policy-agent/gatekeeper/commit/451614181e5d63b21c3e14f5c87ad36eb7d29793,
make docker-push-release does not push the "latest" tag anymore.
Following the instructions have the effect of pushing only the VERSION tag but not latest.
make docker-push pushes latest, having the desired effect.

Fix instructions on how to deploy from master.

---

pkg/mutation/assign_mutator.go
pkg/mutation/assignmeta_mutator.go
pkg/mutation/match.go
pkg/mutation/match_test.go
pkg/mutation/mutation.go
pkg/mutation/mutator.go
pkg/mutation/system_test.go

Implement both a Matches function and an AppliesTo function that checks if the given object matches a Match / ApplyTo.
This tells if a given mutation will need to be applied to a given object.
Fixes #929
Built on top of 
https://github.com/open-policy-agent/gatekeeper/pull/926
https://github.com/open-policy-agent/gatekeeper/pull/916
The last commit is the relevant one, namely with match.go / match_test.go files.
This assumes that the Match structure will need to be changed according to https://github.com/open-policy-agent/gatekeeper/pull/916/files#r5160 …

Implement the match logic

---

pkg/webhook/mutation.go

This avoids generating the MuatingConfigurationWebhook manifest, which we don't want to do until mutation is beta
Fixes #

Disable mutation webhook generators for now

---

pkg/audit/manager.go
pkg/upgrade/manager.go
pkg/util/selfLink.go
pkg/util/selfLink_test.go

`selfLink` is disabled by default in k8s v1.20 and will be removed in v1.21
Fixes #1002 

Fix for selfLink removal

---

pkg/webhook/common.go
pkg/webhook/mutation.go
pkg/webhook/policy.go
pkg/webhook/stats_reporter.go
pkg/webhook/stats_reporter_test.go

The PR is opened for discussion on [this comment](https://github.com/open-policy-agent/gatekeeper/pull/970#discussion_r527140255).
It extracts some common code for validation and mutation stats reporting.
Depends on #881

Common stats reporting for validation and mutation

---

README.md

This change adds a small comment about the name of the Config resource to make it obvious that it is ignored in the reconcile loop otherwise.
Fixes #923

Add comment about config name

---

pkg/controller/assignmetadata/assignmetadata_controller.go
pkg/mutation/system.go
pkg/mutation/system_test.go

When we reconcile deletions, we don't have the full object.
This is causing a panic in parsing. Here we change the Remove method to take the ID of the object instead of the object itself.

Use ID only for cache deletion.

---

pkg/mutation/system.go
pkg/mutation/system_test.go
pkg/webhook/mutation.go

A follow up to #1015 ([here](https://github.com/open-policy-agent/gatekeeper/pull/1015#discussion_r539469397))
Mutation webhook will return no patches when no mutation was done.

Mutation webhook should not return any patches when nothing was mutated

---

.github/workflows/workflow.yaml
Makefile

Fix broken CI due to helm repo deprecation.
helm used to have https://kubernetes-charts.storage.googleapis.com/index.yaml as the default stable repository, which no longer resolves. Use the argument `--stable-repo-url` to specify the new repository `https://charts.helm.sh/stable`.
UPDATE: Using helm v2.17.0 instead
Fixes #

Fix helm stable repo for v2

---

README.md
apis/mutations/v1alpha1/zz_generated.deepcopy.go
pkg/controller/constraint/constraint_controller.go
pkg/readiness/noop_expectations.go
pkg/readiness/object_tracker.go
pkg/readiness/object_tracker_test.go
pkg/readiness/objset.go
pkg/readiness/ready_tracker.go
pkg/readiness/tracker_map.go

Add the readiness-retries flag, allowing the user to configure how many 
attempts should be made to injest a resource into OPA while blocking the
webhook.
Previously, a failure to injest an object into the OPA cache would
strike that object from the ObjectTracker, a type tasked with blocking
the webhook from serving requests until all the necessary objects had
been observed on the API server.  This setup optimizes for availability
(the webhook serving requests ASAP) over security.
By adding retry functionality, we configure gatekeeper to block the
webhook for longer, but unblock with a more complete set of constraints.

Add retry support to objectTracker

---

pkg/webhook/policy.go
pkg/webhook/policy_test.go

This PR adds a simple check to the validating webhook, ensuring that the
user's Config resource (of group "config.gatekeeper.sh") has the name
"config".  This provides helpful feedback for new users.
Fixes #1018

Check that the Config resource is named 'config'

---

config/manager/manager.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/deploy/gatekeeper.yaml

Audit deployment label should be `audit-controller`
Fixes #

Fix audit deployment label

---

cmd/build/helmify/replacements.go
cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/charts/gatekeeper/values.yaml

This allows users to set different affinities,
nodeSelectors and tolerations for the audit deployment
versus the controller manager deployment.
Also the set affinity on controllermanager was overridden
by a second affinity key. This affinity is now set as
default in the values.

Allow different settings for audit vs controller

---

config/manager/manager.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/deploy/gatekeeper.yaml

It is best practice to set `readOnlyRootFilesystem: true` in the container's security context.
From a brief review of the code, I don't think Gatekeeper writes anything to its filesystem, but it would be best if someone more familiar with the code base can confirm that.

Enable readOnlyRootFilesystem in Helm chart

---

pkg/readiness/object_tracker.go
pkg/readiness/object_tracker_test.go

The object tracker maintains a list of all observed resources of it's
specified gvk.  These observations are removed whenever there is a
corresponding expectation for that resource.  The creation of an
expectation or an observation can come in any order for a resource.
It is possible that a resource can be observed, but that it is not
expected.  I.e. the resource is of the type tracked by the object
tracker, but is not one that should block the webhook.
In this case, we should not prevent the webhook from serving.  The
resource should be seen but not be cause to block the webhook.
Fixes #1023

Allow a tracker with observations but without expectations to be Satisfied

---

README.md

Instructions for the prebuilt-image installation currently use the `v3.1.0` `deploy/gatekeeper.yml`, this PR updates to the latest stable release (`v3.2.0`).

Prebuilt image installation uses the latest stable release (v3.2.0)

---

README.md

Updates the kustomize install url in the readme to use the current docs -  avoids a redirect.

Update kustomize url in readme

---

pkg/controller/config/process/excluder.go
pkg/webhook/common.go
pkg/webhook/mutation.go
pkg/webhook/policy.go

Should the mutation webook have a separate process excluder to allow skipping a different set of namespaces?
Please share your thought on this PR
Depends on #881

New process excluder for mutation

---

apis/mutations/v1alpha1/assign_types.go
apis/mutations/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/mutations.gatekeeper.sh_assign.yaml
pkg/mutation/assign_mutator.go
pkg/mutation/assign_mutator_test.go
pkg/mutation/assignmeta_mutator.go
pkg/mutation/conversion_test.go
pkg/mutation/mutation_function.go
pkg/mutation/mutation_function_test.go

This PR adds value testing to the assign mutator, per the mutation design.
Note that the schema of the value tests has been changed slightly, I now assume a format like:
```yaml
spec:
parameters:
assignIf:
in: ["one", "two"]
notIn: ["three"]
```
Fixes #1080 

Add value testing to the assign mutator

---

pkg/readiness/ready_tracker.go

Minor fix using slice element itself or local copies instead of iteration variable pointers in `readiness.Tracker`
Fixes #1024 

Avoid passing pointer in iteration

---

pkg/mutation/assign_mutator.go
pkg/mutation/assignmeta_mutator.go
pkg/mutation/system.go
pkg/mutation/types/mutator.go

The mutations error messages are sometimes missing information about the mutation for which a failure occurred. 
This patch add some more info to some of the error messages.

Add more details to mutation related errors

---

test/bats/test.bats
test/bats/tests/constraints/all_cm_gatekeeper_label_unique.yaml
test/bats/tests/constraints/all_cm_must_have_gatekeeper-dryrun.yaml
test/bats/tests/constraints/all_cm_must_have_gatekeeper.yaml
test/bats/tests/constraints/all_cm_must_have_gatekeeper_audit.yaml
test/bats/tests/constraints/containers_must_be_limited.yaml
test/bats/tests/sync.yaml
test/bats/tests/sync_with_exclusion.yaml
test/bats/tests/templates/k8scontainterlimits_template.yaml
test/bats/tests/templates/k8srequiredlabels_template.yaml
test/bats/tests/templates/k8suniquelabel_template.yaml

This will allow the tests to be re-run.
Signed-off-by: Julian Dolce <jdolce@qnx.com>
Cleans up after an e2e test run so that tests can be re-run and will pass.
Fixes #1119

fix: e2e teardown.

---

pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/readiness/noop_expectations.go
pkg/readiness/object_tracker.go
pkg/readiness/object_tracker_test.go
pkg/readiness/ready_tracker.go
pkg/readiness/ready_tracker_unit_test.go
pkg/readiness/tracker_map.go

Add readiness retries support for Constraint Templates

---

.github/workflows/upgrade.yaml
Makefile
test/bats/test.bats

Uses matching version for initial test
Fixes #

fix helm upgrade

---

.github/workflows/workflow.yaml

During release, ran into issue with the `tagged release` job step `Verify release` with error:
```console
note: module requires Go 1.16
make: *** [Makefile:195: manifests] Error 2
Error: Process completed with exit code 2.
```
Fixes #

Fix gh workflow tagged release

---

website/docs/mutation.md

Signed-off-by: Takao Shibata <chise.alter.pasta@gmail.com>
Heading in following website is broken. This PR fix it.
- https://open-policy-agent.github.io/gatekeeper/website/docs/mutation
I add space to fix broken heading and set heading level as level 2 according to other headings.
None
None

website: fix markdown heading

---

pkg/audit/manager.go

Fixes #1203 - log ucloop.uc in audit

---

Makefile

Since we have 2 `repository` keys in helmify values.yaml now, `make release-manifest` tries to replace both
https://github.com/open-policy-agent/gatekeeper/pull/1233#discussion_r610014498
Fixes #

fix release manifest

---

test/bats/test.bats

Remove deprecated kubectl generators from e2e

---

go.mod
main.go
vendor/modules.txt

Set klog logger to align with existing logger. This applies to logs coming from client-go.
Before:
```
W0416 02:20:51.562994       1 warnings.go:67] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
{"level":"info","ts":1618539651.6613297,"logger":"controller-runtime.manager.controller.cert-rotator","msg":"Starting EventSource","source":{}}
W0416 02:20:51.662346       1 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0416 …
```

set klog global logger

---

pkg/mutation/assignmeta_mutator.go

we are checking `isValidMetadataPath` already in line 126
Fixes #

remove duplicate isValidMetadataPath in assignMetadata

---

Makefile
cmd/build/helmify/kustomize-for-helm.yaml
cmd/build/helmify/replacements.go
cmd/build/helmify/static/values.yaml
main.go
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/charts/gatekeeper/values.yaml
pkg/util/flagSet.go
pkg/webhook/namespacelabel.go
test/bats/test.bats
test/bats/tests/bad/bad_http_send.yaml
test/bats/tests/templates/use_http_send_template.yaml

Signed-off-by: Becky Huang <beckyhd@google.com>
Provide the flag allowing us to set `--disable-builtin=http.send` to toggle off opa http.send builtin
Fixes #1137
Reused the flag struct implemented by exempt-namespace, it's now moved to util package.

Provide the flag for disable unsafe builtins

---

docs/design/README.md

This reverts commit 64edbe3db4c0f83cb6ade0bf6dbaf807752da36b.
DCO not signed, committed without review
Fixes #

Revert "Add v1 CRD deprecation doc"

---

deploy/experimental/gatekeeper-mutation.yaml

The image tag from git tag v3.4.0 is v3.4.0-rc.1, this PR fixes this.
(This is also a flag to think about this on the next release 😉 )

Fix gatekeeper mutation image tag

---

third_party/sigs.k8s.io/controller-runtime/README.md
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/cache.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/cache_suite_test.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/cache_test.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/doc.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/informer_cache.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/informer_cache_test.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/informer_cache_unit_test.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/internal/cache_reader.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/internal/deleg_map.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/internal/informers_map.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/multi_namespace_cache.go

Rebases the dynamic cache patch over controller-runtime v0.8.2.
Does not upgrade the direct controller-runtime dependency, that will be handled in a separate PR.

Rebase controller-runtime/pkg/cache fork over v0.8.2

---

charts/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
charts/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml

PR #1250 accidently updated `charts` folder, reverting those changes
They are in `manifest_staging` so it'll be swapped when a new release is cut
Fixes #

revert #1250 on charts

---

pkg/audit/manager.go
pkg/controller/constraintstatus/constraintstatus_controller.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller.go
pkg/controller/mutatorstatus/mutatorstatus_controller.go
pkg/readiness/ready_tracker.go
pkg/upgrade/manager.go
pkg/watch/manager_integration_test.go

While range loops are convenient ways of accessing each element in a
list, they can lead to immensely wasteful copying if not handled
carefully. In some cases, we're copying ~400 bytes just to access a
single field!
This PR fixes the issues found by the rangeValCopy linter. Usually, this
is resolved by indexing the list inline. In cases where the entire entry
is required, or many fields are accessed, I've created a variable which
creates a reference to the item in the list without copying it.
In one case, after the implicit shallow copy of the list, we then
explicitly create another shallow copy. I've made it so we only perform
a single shallow copy, as the code seems to intend.
Full list of fixes below. Each line includes how large the copied …

Resolve rangeValCopy lint suggestions

---

go.mod
go.sum
vendor/modules.txt

This dependency is unused, and was likely added in error.

Remove unused stretchr/testify from go.mod

---

pkg/webhook/common.go
pkg/webhook/mutation.go
pkg/webhook/mutator_validation_test.go
pkg/webhook/policy.go
pkg/webhook/policy_test.go

The admission.Request type is 400 bytes, making it huge to pass by value
to functions. Each time this is passed to another function, the runtime
fully copies this object, often many times due to the function depth. In
general, we should avoid such unnecessary struct copying.
This PR reduces this copying (for example) by limiting several functions
to only ask for the subfield of admission.Request they need - the 3 bytes
referencing the Raw object byte slice. Other changes in this PR are
analogous.
I've only done the optimization where it added no complexity to the
call sites. For example, it would be valid to pass a pointer to the
admission.Request, but this could potentially have side effects as
the function would be able to mutate the input. In …

Reduce copying of admission.Request

---

.github/workflows/workflow.yaml
.gitignore
.golangci.yaml
Makefile

This means we don't need to manually install golangci-lint every time we
run our git workflow - we just use a generally-available one that
already has it installed.
It also means that "make lint" will work the same for everyone and the
workflow without additional coordination. Before this PR, it was
possible for maintainers to be on a different version of golangci-lint
than the one used by the GitHub workflow and so "make lint" would
provide inconsistent results.

Lint code using dockerized golangci-lint

---

.github/workflows/workflow.yaml
Makefile

This PR adds a separate github workflow for testing k8s 1.22 via a
custom-built k8s 1.22 node image.  1.22 isn't currently available under
kindest/node on docker hub, as 1.22 hasn't been officially released.
sozercan built and pushed this image from the k8s GitHub repo.  Once k8s
1.22 is available via the typical kindest/node pathway, the changes in
this PR should be removed.

Add kind 1.22 Github Workflow

---

pkg/controller/assign/assign_controller.go
pkg/controller/assignmetadata/assignmetadata_controller.go
pkg/mutation/mutators/assign_mutator.go
pkg/mutation/mutators/assignmeta_mutator.go
pkg/mutation/mutators/conversion_test.go
pkg/mutation/mutators/testhelpers/dummy_mutator.go
pkg/mutation/path/parser/node.go
pkg/mutation/path/parser/parser.go
pkg/mutation/path/parser/parser_test.go
pkg/mutation/path/tester/tester.go
pkg/mutation/path/tester/tester_test.go
pkg/mutation/path/token/scanner.go
pkg/mutation/path/token/scanner_test.go
pkg/mutation/schema/schema_test.go
pkg/mutation/system_test.go
pkg/mutation/types/mutator.go
pkg/mutation/types/mutator_test.go
pkg/readiness/ready_tracker_test.go

*Forbid creating mutations which require specific paths but forbid their parents.* For example, requiring `spec.foo` does not exist but also requiring that `spec.foo.bar` must exist.
*Improve error handling and validation in pkg/mutations/path.* Use new Go 1.13-style base and wrapped errors, which allows us to directly check for specific errors in tests using `errors.Is`. In the future, we may also use errors.Is for control flow as we can handle errors safely while still annotating them as needed.
*Make mutation path error messages more explicit.* Define `Node.String()` for printing out specific paths in error messages, helping users debug offending path tests. Additionally, test that `Parse(node.String())` yields an equivalent structure.
**Which …

[mutation] validate parent and children Conditions

---

.golangci.yaml
apis/status/v1beta1/util.go
main.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller_test.go
pkg/mutation/match/match.go
pkg/mutation/match/match_test.go
pkg/mutation/mutators/assign_mutator.go
pkg/mutation/mutators/assignmeta_mutator.go
pkg/mutation/mutators/core/mutation_function.go
pkg/mutation/mutators/core/mutation_function_test.go
pkg/mutation/mutators/testhelpers/dummy_mutator.go
pkg/mutation/system.go
pkg/readiness/object_tracker.go
pkg/readiness/objset.go
pkg/readiness/ready_tracker_test.go
pkg/readiness/ready_tracker_unit_test.go
pkg/target/target_integration_test.go
pkg/webhook/mutation.go
pkg/webhook/namespacelabel.go
pkg/webhook/policy.go
pkg/webhook/policy_benchmark_test.go
pkg/webhook/stats_reporter.go

Activating the gocritic linter adds a few new performance and readability linters to golangci-lint. For this PR, it found several cases where we're passing large structs, and identified if statements that could be expressed more simply.
I've deactivated "commentFormatting" as this doesn't play nice with commented-out code.

Add gocritic linter

---

config/overlays/mutation_webhook/webhook.yaml
deploy/experimental/gatekeeper-mutation.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml

Add default configs to mutatingwebhookconfig

---

pkg/mutation/path/tester/tester.go

MaxInt64 breaks on 32-bit systems unless explicitly typecast to an
int64.
In this case, we do not expect users will ever need to reference nodes
more than 2 billion layers deep with gatekeeper. Thus, it feels safe to
make this assumption and use MaxInt32 as the starting value for the
minimum. We will encounter other problems long before this gives us
problems.
Fixes #

Use MaxInt32 instead of MaxInt64

---

pkg/controller/constraint/constraint_controller.go
pkg/controller/constraintstatus/constraintstatus_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller.go

Cherry pick of #1240 for v3.4.1
Fixes #

Cherry pick of #1240: Do not allow status objects from other pods to trigger constraint reconciles

---

config/overlays/mutation_webhook/webhook.yaml
deploy/experimental/gatekeeper-mutation.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml

Cherry pick of #1360: Add default configs to mutatingwebhookconfig

---

cmd/gatekeeper-test-alpha/gatekeeper-test-alpha.go
pkg/gktest/files.go
pkg/gktest/filter.go
pkg/gktest/result.go
pkg/gktest/run.go

Parse gatekeeper-test flags per [the design](https://docs.google.com/document/d/15nWc9TH97LF9o58CTVxYxFM9tYk8-seB5erIa2gouPo/edit?usp=sharing).
This PR sets up several function and type stubs to be worked on in the
future. The intent here is to make it easy for development to be able to
happen in parallel PRs. The comments on these stubs is to clarify what
they _should_ do when complete rather than what they currently do.
These are the code paths which can be worked on in parallel after this
PR:
1. Listing the set of files to test
2. Creating the Filter to select suites and tests to run
3. Running test suites and printing test output
Fixes: #1369

Parse gatekeeper-test flags

---

.github/workflows/workflow.yaml
Makefile
cmd/build/helmify/kustomize-for-helm.yaml
config/overlays/mutation_webhook/kustomization.yaml
config/overlays/mutation_webhook/status.gatekeeper.sh_mutatorpodstatuses.yaml
manifest_staging/charts/gatekeeper/crds/mutatorpodstatus-customresourcedefinition.yaml

Ensure mutatorpodstatus crd is included in the helm chart.
*NOTE*: removing `build_mutation_test` job from github workflow. Enabling and running mutation tests by default. 
Fixes #1387 

Add mutatorpodstatus to helm chart

---

website/docs/install.md

The installation instructions should point to the latest release.

Update documentation for 3.5

---

pkg/mutation/mutators/assign_mutator.go
pkg/mutation/mutators/assign_mutator_test.go
pkg/mutation/mutators/core/mutation_function.go
pkg/mutation/path/parser/errors.go
pkg/mutation/path/parser/node.go
pkg/mutation/path/parser/parser.go
pkg/mutation/path/parser/parser_test.go
pkg/mutation/path/token/scanner.go
pkg/mutation/path/token/scanner_test.go
pkg/mutation/schema/schema.go
pkg/mutation/schema/schema_test.go

Previously, the mutation path parser only supported string types for
keyValues selecting items in a list. This PR adds support for integers,
such that we can now express paths like this:
```
spec.containers[name: opa].ports[containerPort: 8888].name
```
Integers are assumed to be represented in decimal and are interpreted as
positive int64 values.
The mutation code was updated accordingly to match based on type.
Additionally, string serialization of paths was updated to be more
selective on which strings are quoted.
Fixes #1355
Signed-off-by: Oren Shomron <shomron@gmail.com>

Add integer keyValue support to mutation path parser / mutators

---

cmd/gator/test/test.go
pkg/gktest/read_suites.go
pkg/gktest/read_suites_test.go

Implement functionality for reading test Suites. This includes reading
single file, reading suites in a single directory, and reading suites in
a directory and its subdirectories.
Note that it is intentional that the Suite type is still empty - a
parallel CL will begin adding fields and functionality to it. This CL is
just focused on reading Suites from the disk.
I've opted to not test certain edge cases - for example permission
errors - as we'd either have to define our own fs.FS implementation or
have unit tests that write/read from disk. As-is, unit tests cover the
core logic paths and 90% of the code.

[gk-test] Read test files

---

website/docs/install.md

Fixes #1431
Update docs to specify that 1.16 is the new minimum supported k8s version.

Update GK minimum version and reasoning.

---

.golangci.yaml
pkg/mutation/mutators/core/mutation_function_test.go
pkg/mutation/path/tester/tester.go
pkg/mutation/schema/schema.go
pkg/mutation/system_test.go

Unchecked type assertions can lead to panics which yield obtuse errors.
This commit enables the forcedtypeassert to ensure we always check type
assertions and have the opportunity to provide useful error messages.
Also enable exportloopref to catch potential bugs when using references
to loop variables, which can behave unexpectedly and lead to
inconsistent bugs.
Fixes #

Enable force type assertions linter

---

.github/workflows/workflow.yaml
Makefile

The flag is `--load-restrictor`, not `--load_restrictor`
Without change, `make deploy-mutation` shows:
```
kustomize build --load_restrictor LoadRestrictionsNone config/overlays/mutation | kubectl apply -f -
Error: unknown flag: --load_restrictor
```
With the change, `make deploy-mutation` succeeds.
I'm using kustomize v4.1.3:
```
gatekeeper$ kustomize version
{Version:kustomize/v4.1.3 GitCommit:0f614e92f72f1b938a9171b964d90b197ca8fb68 BuildDate:2021-05-20T20:52:40Z GoOs:linux GoArch:amd64}
```

Use containerized kustomize

---

pkg/mutation/mutators/assign_mutator_benchmark_test.go

Add benchmark tests for AssignMutator.Mutate.
In writing this, I found that mutating objects takes about 10x longer
than not mutating objects. Profiling reveals that we spend over 90% of
compute time in AssingMutator.Value(), where we convert from the raw
JSON value to a literal Go struct.
In a separate PR I'll suggest a change that resolves this performance
issue. Most likely we'll want to cache the assigned value. We can then
either reflect.DeepCopy the value or assign the cached value directly,
depending on whether we feel it safe.

Benchmark AssignMutator.Mutate code

---

pkg/mutation/mutators/assignmeta_mutator.go
pkg/mutation/mutators/assignmeta_mutator_benchmark_test.go

Note: depends on #1441 
Per findings in #1441, we can greatly improve the speed of AssignMetadata.Mutate by caching the tester instead of recreating it every time we call Mutate.
This reduces the runtime when no mutation is made by 97%, and when mutations are made by 30%!
```
$ for i in {1..20}; do echo $i; go test github.com/open-policy-agent/gatekeeper/pkg/mutation/mutators --bench=BenchmarkAssignMetadata >> before.out; done
$ git checkout benchmark-metadata-2
$ for i in {1..20}; do echo $i; go test github.com/open-policy-agent/gatekeeper/pkg/mutation/mutators --bench=BenchmarkAssignMetadata >> after.out; done
$ benchstat before.out after.out 
name                        old time/op  new time/op  delta
AssignMetadataMutator_Always-12    6.64µs ± 2%  4.70µs ± 1%  -29.22%  (p=0.000 …
```

[mutation] Cache tester in AssignMetadata like we do in Assign mutators

---

pkg/mutation/mutators/assign_mutator.go

I forgot to remove this debug line in a previous commit.

[mutators] Remove erroneous print statement

---

cmd/gator/test/test.go
pkg/gktest/errors.go
pkg/gktest/opa.go
pkg/gktest/read_constraints.go
pkg/gktest/runner.go
pkg/gktest/runner_test.go
pkg/gktest/suite.go

Now that much of the test running logic is defined, it is more apparent
how to organize it.
Code specific to running tests, but which does not change with the
nature of the tests being run or how the results are printed, should
live in its own place. It may be decorated in the future with objects
(like Printers) which are specified by the user.
This PR has zero changes to logic - it only moves logic around.

[gk-test] Refactor run code into Runner

---

pkg/mutation/system.go
pkg/mutation/system_benchmark_test.go
pkg/mutation/system_test.go

Depends on #1452.
Add a basic benchmark test for System.Mutate.
In this case benchmarking pointed to an easy way to improve performance dramatically, so I've bundled the changes together in this PR.
Most of the time we spend in System.Mutate is in cmp.Equal. However, we know that "old" and "obj" are identical if no Mutators were run. This means if in an iteration no Mutators reported making any changes, we can immediately assume:
1) If we are on the first iteration, then old == obj == original, and so no changes were made to the object.
2) Otherwise, we know that (old == obj), and both are distinct from original (since we verified this in the first iteration).
```
$ benchstat before.txt after.txt 
name              old time/op  new time/op  delta
System_Mutate-12  8.77µs ± 3%  1.14µs ± 7% …
```

Reduce System.Mutate runtime by 87%

---

pkg/gktest/errors.go
pkg/gktest/filter.go
pkg/gktest/printer.go
pkg/gktest/printer_go.go
pkg/gktest/printer_go_test.go
pkg/gktest/read_constraints.go
pkg/gktest/result.go
pkg/gktest/runner.go
pkg/gktest/runner_test.go
pkg/gktest/suite.go

Depends on #1445.
Add logic for running individual test cases. Now that we've compiled the
constraints, all we need to do is Review() the specified objects and
compare the Results with what the user specified.
This PR does not add Assertion functionality - we'll do that for alpha,
not pre-alpha.
Also add unit tests that verify we are, in fact, running the test cases.

[gk-test] Run case

---

website/docs/debug.md

**What this PR does / why we need it**: it fixes an error in the docs
Fixes #
**Special notes for your reviewer**: https://github.com/open-policy-agent/gatekeeper/blob/master/apis/config/v1alpha1/config_types.go#L45-L52

fix whitespace error in the debugging docs

---

.github/workflows/workflow.yaml

- We were using an alpha image before, updating with official release
- Dropping v1.19
Fixes #

update CI with k8s v1.22.0

---

test/bats/tests/templates/use_http_send_template.yaml

Signed-off-by: Ivan Font <ifont@redhat.com>
The bats tests rely on common labels to cleanup the test resources such as `constrainttemplates` that are created throughout the bats tests. This particular CT was missing that common label and as a result was not being deleted at the end. This now adds the label so the bats tests can remain idempotent.
Ref #1119.

Add label to bats http.send test for idempotence

---

pkg/webhook/stats_reporter.go

Signed-off-by: Tsubasa Umeuchi <tsubasa.umeuchi@gmail.com>
The upper limit for the metrics `validation_request_duration_seconds_bucket` and `mutation_request_duration_seconds_bucket` is set to 0.05 seconds.
On the other hand, this value is very low considering real-world use cases. So most of the actual requests will exceed the upper limit of 0.05 seconds and will be aggregated into the `+Inf` bucket.
The following is the environment of a cluster managed by the org to which I belong. In this environment, the number of requests within a certain period of time was about 50,000, but there were only 3 requests that were processed within 0.05 seconds, which is the current limit.
- Number of Nodes: 185
- Number of running Pods (avg): 2500
- Number of …

Update the upper limit of request duration metrics to 3 seconds

---

cmd/gator/gator.go
cmd/gator/test/test.go
pkg/gktest/client.go
pkg/gktest/printer_go.go
pkg/gktest/printer_go_test.go
pkg/gktest/read_suites.go
pkg/gktest/read_suites_test.go
pkg/gktest/result.go
pkg/gktest/runner.go
pkg/gktest/runner_test.go
pkg/gktest/suite.go

Make it possible to run gator test successfully.
A note on timings: The sum of the times for a case adds up to significantly less than the reported runtime for the test. This is because the test runtime includes compiling the Template and instantiating the Constraint, but individual cases do not. Times for suites are approximately the sum of their test runtimes as there is no significant overhead.
Failure:
```
$ gator test suite.yaml
--- FAIL: allow object	(0.00417s)
got violations: All namespaces must have an `owner` label that points to your company username
--- FAIL: deny if name is forbidden	(0.0778s)
FAIL		0.0778s
FAIL
```
Verbose Failure:
```
$ gator test suite.yaml  -v
=== RUN   deny if name is forbidden
=== RUN   allow object
--- FAIL: allow object	(0.0029s)
got violations: All …
```

run gator test

---

website/docusaurus.config.js

Currently, if someone clicks on the Gatekeeper icon it is going to a broken URL
Fixes #

fixing the base url for the gatekeeper icon

---

cmd/build/helmify/static/templates/upgrade-crds-hook.yaml
manifest_staging/charts/gatekeeper/templates/upgrade-crds-hook.yaml

Signed-off-by: Julian Dolce <jdolce@qnx.com>
The Helm Chart currently has a hook to update the crds using image gatekeeper-crds. However it doesn't provide a way to add image pull secrets. This causes an issue if you have a constraint that restricts which image repo's are allowed, causing the hook to fail. This change allows users to specify the image pull secrets just for the crd migration hook. 

fix: Add gatekeeper-crds image pull secrets to Helm Chart

---

cmd/gator/test/test.go
pkg/gktest/errors.go
pkg/gktest/filter.go
pkg/gktest/filter_test.go
pkg/gktest/result.go
pkg/gktest/runner.go
pkg/gktest/runner_integer_test.go
pkg/gktest/runner_test.go

Define --run filter for `gator test`.
The filter is often run twice on case names - first to check if a Test should be run, and then when running the Case itself. I've done this in the interest of simpler filtering code. This isn't likely to be a performance bottleneck.
Also, note that the regex passed to --run is matches against strings of the form "$TEST_NAME//$CASE_NAME". I considered splitting the value passed to --run and matching against test name and test name separately, but this resulted in much more complex code. As-is accomplishes the behavior specified in the design.
Fixes: #1381

[gator-test] add filter

---

pkg/readiness/ready_tracker_test.go
pkg/readiness/testdata/99-all_ns_must_have_gatekeeper.yaml
pkg/readiness/testdata/99-configmap.yaml
pkg/readiness/testdata/99-prod_repo_is_openpolicyagent.yaml
pkg/readiness/testdata/post/99-k8shttpsonly_constraint.yaml

Different versions of the control-plane used by envtest may introduce
"noise" (e.g. configmaps in kube-system) that affect some of our tests
expecting to see only fixtures. Where appropriate, scope the client used
by the test to a particular namespace in which we control the fixtures
entirely.
Signed-off-by: Oren Shomron <shomron@gmail.com>

Scope pkg/readiness/Test_CollectDeleted to a controlled namespace

---

.github/workflows/workflow.yaml
Makefile
cmd/build/helmify/main.go

Upgrade to the most recent version and fix linter errors.

Upgrade to golangci-lint v1.42.1

---

cmd/gator/test/test.go
pkg/gktest/client.go
pkg/gktest/errors.go
pkg/gktest/filter_test.go
pkg/gktest/printer_go_test.go
pkg/gktest/read_constraints.go
pkg/gktest/read_suites_test.go
pkg/gktest/runner.go
pkg/gktest/runner_integer_test.go
pkg/gktest/runner_test.go
pkg/gktest/suite.go
third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/cache.go

Support `gator test` for referential constraints.
To keep tests hermetic, we now instantiate a new OPA client for each test case. Otherwise, we risk crosstalk between tests if resetting Data in the OPA client fails.
Other minor changes:
- Make tests run in parallel
- Require Runner to be instantiated with builder method to ensure required dependencies are passed

[gator test] Support referential constraints

---

pkg/mutation/mutators/modifyset/modify_set_mutator.go
pkg/mutation/mutators/modifyset/modify_set_test.go

ModifySet has the following bugs:
* It has an index error if pruning an item from the end of a list
* It assumes that the input list is a well-formed set, which may not
be true.
Fixes #

Fix bugs in ModifySet mutator

---

pkg/gktest/runner.go
pkg/gktest/runner_integer_test.go
pkg/gktest/runner_test.go

Forbid empty assertions, per discussion. Empty assertions in a test case is an error. Users must explicitly specify whether a case is intended to return a violation or not.

Forbid empty assertions

---

apis/status/v1beta1/constraintpodstatus_types.go
apis/status/v1beta1/constraintpodstatus_types_test.go
apis/status/v1beta1/constrainttemplatepodstatus_types.go
apis/status/v1beta1/constrainttemplatepodstatus_types_test.go
apis/status/v1beta1/mutatorpodstatus_types.go
apis/status/v1beta1/mutatorpodstatus_types_test.go
apis/status/v1beta1/util.go
apis/status/v1beta1/util_test.go
pkg/controller/config/config_controller_test.go
pkg/controller/constraint/constraint_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller_test.go
pkg/controller/controller.go
pkg/controller/mutators/core/controller_test.go
pkg/controller/mutators/core/reconciler.go
pkg/controller/mutators/core/reconciler_test.go
pkg/fakes/doc.go
pkg/fakes/opts.go
pkg/fakes/pod.go
pkg/mutation/mutators/assign/assign_mutator_test.go
pkg/mutation/mutators/core/mutation_function_test.go
pkg/mutation/system_test.go
pkg/readiness/ready_tracker_test.go
pkg/watch/manager_integration_test.go

This was introduced for tests, but is unnecessary. All that is needed
for setting ownerreferences to work properly is to set the UID of fake
Pods used in testing.
This is because ownerreference validation requires that UID be set on
the reference (to deduplicate objects with identical names/namespaces
which existed at different points in time).
This raises the point that we should probably have a general-purpose
method for instantiating a fake Pod for use in testing and debugging. It
isn't obvious to me where that is. Feel free to suggest a location. Do
note that it would be in production code since the debug setting is
compiled in non-test files.
Note: the fake Pod UID I've added for tests is arbitrary - it just has to be
*something*, but the specific value is meaningless.
This PR is a …

Remove PodOwnership option

---

cmd/build/helmify/kustomize-for-helm.yaml
cmd/build/helmify/static/README.md
cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/README.md
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/charts/gatekeeper/values.yaml

enable external data flag for helm

---

.github/workflows/website.yaml

docusaurus requires node >= 14 now, bumping to node 16 (active LTS).
`error @docusaurus/core@2.0.0-beta.9: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.7"`
Fixes #

bump node version to 16

---

main.go
pkg/webhook/policy.go

We missed some switching code in main.go
that turns webhooks on/off when a webhook is
enabled. As-written, webhooks are only enabled
if the validating webhook is enabled, this fixes that.
Fixes #

Allow mutation to run as a standalone pod

---

go.mod
go.sum
pkg/controller/constraint/constraint_controller.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/backend.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/drivers/local/args.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/drivers/local/errors.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/drivers/local/local.go
vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/errors.go
vendor/modules.txt

This is to decouple Gatekeeper from the error implementation in
frameworks. With this change, frameworks can swap out the implementation
without Gatekeeper caring. Gatekeeper doesn't use any of the fields of
this error type, so it shouldn't rely on the specific type.

Use IsUnrecognizedConstraintError

---

website/docs/externaldata.md
website/versioned_docs/version-v3.7.x/externaldata.md

Dashes in variable names are not allowed. `my-list` would be parsed
as `my` minus `list`.

website/externaldata: fix rego snippet

---

go.mod
pkg/controller/constrainttemplate/constants.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go

Gatekeeper relies on frameworks adding no new information to errors
returned by OPA - directly testing that the error type returned by
client.CreateCRD is the type given by the underlying OPA library.
This coupling means the implementation of error handling in
frameworks breaks gatekeeper tests.
This PR removes the coupling, instead always using a generic
"create_error" for problems creating CRDs. While this means the error code in
the CreateCRDError type provided by frameworks/ will always be set to
"create_error" - rendering it unhelpful - it would be better for
frameworks/ to provide an API for this as then such logic would not be
split across two repositories.
Fortunately the only behavior that changes because of this PR is the code
shown in the CreateCRDError, which doesn't appear to …

Remove internal error handling coupling

---

go.mod
go.sum
vendor/modules.txt

Module vendoring was put in an inconsistent state, so this fixes it.

go mod tidy & go mod vendor

---

pkg/webhook/policy.go

Recently while integrating `gatekeeper` I noticed that a denied admission webook response will look somewhat like this:
`Message` and `Reason` kinda have the same info.
```
errors.StatusError{
ErrStatus:v1.Status{
TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"},
ListMeta:v1.ListMeta{
SelfLink:\"\",
ResourceVersion:\"\",
Continue:\"\",
RemainingItemCount:(*int64)(nil)},
Status:\"Failure\",
Message:\"admission webhook \\\"validation.gatekeeper.sh\\\" denied the request: [enforce-resource-quota] resource exceeded cpu quota\",
Reason:\"[enforce-resource-quota] resource exceeded cpu quota\",
Details:(*v1.StatusDetails)(nil),
Code:403}
}
```
I guess this is generally ok! However, if one is using ` "k8s.io/apimachinery/pkg/api/errors"` to determine the …

Set Forbidden as the response status reason

---

website/sidebars.js

I hadn't realized that these are pointing to the IDs declared in markdown
Signed-off-by: Will Beason willbeason@google.com

Fix broken sidebar

---

.github/workflows/workflow.yaml
Makefile
pkg/audit/stats_reporter_test.go
pkg/controller/constraint/stats_reporter_test.go
pkg/controller/constrainttemplate/stats_reporter_test.go
pkg/controller/mutators/stats_reporter_test.go
pkg/controller/sync/stats_reporter_test.go
pkg/operations/operrations_test.go
pkg/webhook/stats_reporter_test.go

The new golangci-lint is more strict about variable naming reqiurements.
It has false negatives on some of our duration variables, so I've
renamed them.
We _could_ suppress the linter in these cases, but it's easier to just
rename the variables.
The other fixes are making all variables in a block of declarations have
explicit types if one does. This seems reasonable since not everyone is
familiar with the convention (which is dependent on the type of
declaration).
Fixes #

Update golangci-lint to v1.43.0

---

website/docs/audit.md
website/versioned_docs/version-v3.7.x/audit.md

Update audit doc to add new flags and defaults

---

website/docusaurus.config.js

Algolia is migrating to a new search platform, updating apikey.
This key is not a secret: https://docusaurus.io/docs/2.0.0-beta.8/search#connecting-algolia
Fixes #

update apiKey for website search

---

website/docs/mutation.md
website/versioned_docs/version-v3.7.x/mutation.md

Fixes #1702
Fixes #1700
Fixes #

Document ModifySet and assign.fromMetadata

---

docs/design/README.md

- also moves v1beta1 CRD deprecation doc into the "Implemented"
category, as we've already finished it

Add gator-validate doc to docs/design

---

pkg/gktest/runner_test.go
pkg/target/target.go

Set the Namespace in requests, and add a test for `gator` that validates this behavior works as expected.

fix: Set namespace field in request

---

cmd/gator/test/test.go
pkg/gator/assertion.go
pkg/gator/assertion_test.go
pkg/gator/client.go
pkg/gator/errors.go
pkg/gator/filter.go
pkg/gator/filter_test.go
pkg/gator/intstr.go
pkg/gator/opa.go
pkg/gator/printer.go
pkg/gator/printer_go.go
pkg/gator/printer_go_test.go
pkg/gator/read_constraints.go
pkg/gator/read_suites.go
pkg/gator/read_suites_test.go
pkg/gator/result.go
pkg/gator/runner.go
pkg/gator/runner_integer_test.go
pkg/gator/runner_test.go
pkg/gator/suite.go

Since the `gator` CLI now has a name and will do more than just `gator test`, it's a good idea that we rename `pkg/gktest` to `pkg/gator` to accommodate the other subcommands we'll want to add. Since there's no open PRs against `gator`, now is a great time to make this change.
Fixes #1722

refactor: Rename 'gktest' to 'gator'

---

.github/workflows/upgrade.yaml

#1739 bumped k8s version of helm upgrade test from v1.21 to v1.23, which doesn't support CRD v1beta1 anymore
bumping GK base version to 3.5 which support v1 CRDs
Fixes #

fix: helm upgrade test

---

cmd/build/helmify/kustomization.yaml
cmd/build/helmify/kustomize-for-helm.yaml
cmd/build/helmify/replacements.go
cmd/build/helmify/static/templates/upgrade-crds-hook.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/charts/gatekeeper/templates/upgrade-crds-hook.yaml

… Gatekeeper helm charts #1659
This commit checks if image.release is defined in the values.yaml
if not defined it will ignore the image.release field and only use the values of
image.repository and image.crdRepository to set the "image" in gatekeeper audit /controller
deployment yamls.
With the current implementation there is only one field defined "image.release" which restrics the use of
image-tag:release and not allowing SHA along with "image"(e.g image@SHA) for GK and GK-CRD repository
Signed-off-by: Priya Shet priya.shet@gmail.com
What this PR does / why we need it:
Which issue(s) this PR fixes (optional, using fixes #1659 (, fixes #1659) format, will close the issue(s) when the PR gets merged):
Fixes #1659
Special notes for your reviewer:

feat: Ability to use Image SHA for gatekeeper and gatekeeper-crd images

---

pkg/webhook/policy.go

It's not panic for now, but it's better to check value of resp to avoid may panic in feature.
Fixes #

fix: Check resp before call resp.TraceDump to avoid panic

---

Makefile
cmd/gator/gator.go
cmd/gator/verify/verify.go

In this week's community meeting, we discussed naming that would
differentiate the current `gator test` from a new command that validates
entire manifests against sets of policies (#1786).  We decided to align
gator's commands with the verbs used in conftest.
Accordingly, what has previously been known as `gator test` will be
henceforth called:
`gator verify`
This PR changes package names and the name of the command.  The
aforementioned PR will rebase on this PR to include the name changes.

refactor: Change `gator test` to `gator verify`

---

website/docs/gator.md
website/versioned_docs/version-v3.7.x/gator.md

A previous PR (#1799) changed the gator test command to now be `gator
verify`.  That PR left out docs changes.  Those docs updates are
included here.

docs: gator test --> gator verify

---

cmd/gator/test/test.go

With the replacement of the original `gator test` with the new command
(the original `gator test` now being called `gator verify`), we have
introduced an opportunity for user confusion.  We added some information
to help our users avoid problems in a previous PR: #1836
This PR seeks to further assist users by adding some argument validation
and more --help information.  More specifically, now we forbid arguments
from being passed to the `gator test` command.  This will yield an error
and the "help" message will be printed.  That help message now also
contains a reference to the renaming.
This is useful b/c the usage of `gator verify` _requires_ the use of
positional arguments, where `gator test` _forbids_ them.  This means
that users will fail fast and will be better guided towards the …

Make gator test error when arguments are passed

---

pkg/target/errors.go
pkg/target/target.go
pkg/target/target_test.go

Signed-off-by: Becky Huang <beckyhd@google.com>
Implement TargetHandler ToMatcher, which provides `constraints.Matcher` with .spec.match in mutators
Fixes #1791

perf: Implement ToMatcher and Matcher.Match (#1791)

---

website/docs/install.md
website/versioned_docs/version-v3.6.x/install.md
website/versioned_docs/version-v3.7.x/install.md

It Fixes the typo in the uninstall command.
Any new objects created in 3.7(compared to 3.5) will not be deleted. this addresses that.

fix: uninstall version typos

---

pkg/webhook/testdata/psp-all-violations/psp-templates/host-filesystem-template.yaml
pkg/webhook/testdata/psp-all-violations/psp-templates/host-namespace-template.yaml
pkg/webhook/testdata/psp-all-violations/psp-templates/host-network-ports-template.yaml
pkg/webhook/testdata/psp-all-violations/psp-templates/privileged-containers-template.yaml
pkg/webhook/testdata/psp-all-violations/psp-templates/volume-template.yaml

The benchmark test `BenchmarkValidationHandler` was broken:
Before:
```
$ go test ./pkg/webhook/... -test.bench ^BenchmarkValidationHandler$
goos: darwin
goarch: amd64
pkg: github.com/open-policy-agent/gatekeeper/pkg/webhook
cpu: xxx
BenchmarkValidationHandler/psp:_100%_violations-8                   2634            443209 ns/op
BenchmarkValidationHandler/psp:_100%_violations#01-8                2894            417978 ns/op
BenchmarkValidationHandler/psp:_100%_violations#02-8                2840            411070 ns/op
BenchmarkValidationHandler/psp:_100%_violations#03-8                2733            413003 ns/op
BenchmarkValidationHandler/psp:_100%_violations#04-8                2858            415405 ns/op …
```

test: Fix `BenchmarkValidationHandler` was broken

---

pkg/mutation/mutators/modifyset/modify_set_mutator_benchmark_test.go

The benchmark test `BenchmarkModifySetMutator_Mutate` was broken:
Before:
```
$ go test ./pkg/mutation/mutators/modifyset/... -bench ^BenchmarkModifySetMutator_Mutate$
panic: cannot deep copy runtime.RawExtension
goroutine 98 [running]:
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue({0x1ee51a0, 0xc0004e4150})
/xxx/src/github.com/open-policy-agent/gatekeeper/vendor/k8s.io/apimachinery/pkg/runtime/converter.go:639 +0x273
github.com/open-policy-agent/gatekeeper/apis/mutations/unversioned.(*Values).DeepCopyInto(0xc000337860, 0xc000337ce0)
/xxx/src/github.com/open-policy-agent/gatekeeper/apis/mutations/unversioned/modifyset_types.go:107 +0xd0
github.com/open-policy-agent/gatekeeper/apis/mutations/unversioned.(*ModifySetParameters).DeepCopyInto(0xc00033 …
```

test: Fix `BenchmarkModifySetMutator_Mutate` was broken

---

demo/agilebank/dryrun/bad_resource/duplicate_ing.yaml
demo/agilebank/dryrun/existing_resources/example.yaml
demo/agilebank/dryrun/existing_resources/example1.yaml
demo/agilebank/sync.yaml

This PR is to fix the demo that uses the deprecated Ingress
**Which issue(s) this PR fixes** *
Fixes https://github.com/open-policy-agent/gatekeeper/issues/1903

fix: replace deprecated ingress with new ingress

---

pkg/audit/manager.go

when we deploy we have to wait 15 min to get a new audit, that is a long time to wait and means that our feedback loop for "you deployed something bad" does not kick in fast enough and causes 15min of pain to our end-users if a new constraint was bad (we deploy web+audit together)
so fix this by running the audit once on start
ticker does not have an option to do an initial runs as per  https://github.com/golang/go/issues/17601
/cc @ritazh @sozercan @ctab

fix: do a audit run when we deploy

---

cmd/gator/test/test.go

This logic is useful when leveraging pkg/gator/test, as ReadFiles will
correctly prepare a single file or whole directory tree for usage with
the Test() function exposed in pkg/gator/test.

refactor: Make cmd/gator/test ReadFiles() a public function

---

cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/values.yaml

Match Helm's mwh timeout with yaml (https://github.com/open-policy-agent/gatekeeper/blob/master/deploy/gatekeeper.yaml#L2531)
Fixes #

fix: match helm mwh timeout default value

---

website/package.json
website/yarn.lock

Looks like this broke website deployment
Reverts open-policy-agent/gatekeeper#1914

revert: Revert "chore: bump @mdx-js/react from 1.6.22 to 2.1.0 in /website"

---

pkg/audit/manager.go

Reverting due to #1927
This reverts commit a3d8a0dd9b2d94f3d4a28fc11c7f5e43e1d15e64.
Fixes #

revert: "do a audit run when we deploy (#1901)"

---

pkg/mutation/schema/schema.go

Before:
```
=== RUN   Test_Assign
core.go: ...
==================
WARNING: DATA RACE
Write at 0x00c001438aa8 by goroutine 305:
github.com/open-policy-agent/gatekeeper/pkg/mutation/schema.(*node).Add()
/go/src/github.com/open-policy-agent/gatekeeper/pkg/mutation/schema/node.go:63 +0x6c9
github.com/open-policy-agent/gatekeeper/pkg/mutation/schema.(*DB).upsert()
/go/src/github.com/open-policy-agent/gatekeeper/pkg/mutation/schema/schema.go:108 +0x7d9
github.com/open-policy-agent/gatekeeper/pkg/mutation/schema.(*DB).Upsert()
/go/src/github.com/open-policy-agent/gatekeeper/pkg/mutation/schema/schema.go:78 +0xd6
github.com/open-policy-agent/gatekeeper/pkg/mutation.(*System).Upsert()
/go/src/github.com/open-policy-agent/gatekeeper/pkg/mutation/system.go:92 …
```

fix: fix race condition in mutator controller reconcile

---

Tiltfile
pkg/controller/mutators/cache.go
pkg/controller/mutators/cache_test.go
pkg/controller/mutators/core/reconciler.go
website/docs/metrics.md
website/versioned_docs/version-v3.6.x/metrics.md
website/versioned_docs/version-v3.7.x/metrics.md

We incorrectly upserted mutator ingestion status when the user deleted a mutator, causing the metrics to report an incorrect number of mutators. This PR:
- moves `r.cache.Upsert` from `reportMutator` to `Reconcile`
- initializes all keys in `statusTally` map to 0 in `TallyStatus()` instead of creating an empty map so we can correctly reset the metrics if we remove all mutators
- updates metrics documentation
- performs metrics port-forwarding in Tiltfile if metrics port(s) is defined in `tilt-settings.json`
Example:
```
$ kubectl apply -f test.yaml 
assignmetadata.mutations.gatekeeper.sh/demo-annotation-owner created
```
Metrics:
```
gatekeeper_mutators{status="active"} 1
gatekeeper_mutators{status="error"} 0
```
```
$ kubectl delete -f test.yaml …
```

fix: update gatekeeper_mutators metrics when a mutator is deleted

---

.github/workflows/workflow.yaml
Makefile

The current version we're using is at the end of its support lifecycle.
Also, 1.45 fully supports Go 1.18 for when we need to upgrade.
Fixes #

build: Upgrade golangci-lint

---

config/manager/manager.yaml
manifest_staging/deploy/gatekeeper.yaml

Currently Gatekeeper deployment does not include the `mutation-status` operation by default. Note: helm chart includes it by default. https://github.com/open-policy-agent/gatekeeper/blob/8404d5ee309acdbcc6779337ddcee36a3aaddd88/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml#L53 This updates the deployment yaml to ensure it is included by default.
Fixes https://github.com/open-policy-agent/gatekeeper/pull/1937/files#r838163357

fix: Update deployment to include mutation-status operation

---

pkg/audit/manager.go
pkg/upgrade/manager.go
pkg/util/selfLink.go
pkg/util/selfLink_test.go

Cherry pick #1971 onto 3.8 release branch
* perf:  improve --constraint-violations-limit scaling
With a test cluster where --constraint-violations-limit is set to 500,
there are 400 violating resources (which violate all constraints)
, 100 constraint templates and 10 constraints per template (1k total
constraints) memory usage was getting into the 10s of GBs, this lowers
memory usage for this scenario down to ~1.5 GB and should improve
audit memeory usage scaling with respect to
--constraint-violations-limit.
* fix lint errors
* address review comments
**Which issue(s) this PR fixes** *(optional, using `fixes …

perf:  improve --constraint-violations-limit scaling (#1971)

---

.github/workflows/workflow.yaml

`golangci/golangci-lint-action@v2` installs the latest stable Go version on behalf of the user. That Go version might not always align with Gatekeeper's go version. `golangci/golangci-lint-action@v3` removes that step and relies on manual installation through `actions/setup-go@v2`.
Fixes linting errors in #1981

chore: bump golangci/golangci-lint-action from 2 to 3

---

website/docs/exempt-namespaces.md
website/docs/sync.md
website/versioned_docs/version-v3.6.x/exempt-namespaces.md
website/versioned_docs/version-v3.6.x/sync.md
website/versioned_docs/version-v3.7.x/exempt-namespaces.md
website/versioned_docs/version-v3.7.x/sync.md

While setting up Gatekeeper I had issue as I had renamed my `Config` to another name. After looking at the logs I saw that it ignored my name `exempted-mutation-ns`. When using `config` everything worked fine.
Fixes #

docs: Add a warning to name the Config conf

---

website/versioned_docs/version-v3.8.x/install.md

https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.8/deploy/gatekeeper.yaml should be used when installing v3.8.x.
Fixes #

docs: use release-3.8 manifest in v3.8.x installation doc

---

website/docs/cloud-specific.md
website/versioned_docs/version-v3.6.x/cloud-specific.md
website/versioned_docs/version-v3.7.x/cloud-specific.md
website/versioned_docs/version-v3.8.x/cloud-specific.md

recommends using `NET_BIND_SERVICE` capability to bind to privileged ports instead of removing `securityContext` completely.
None

docs: mention NET_BIND_SERVICE in cloud-specific

---

cmd/build/helmify/static/templates/namespace-post-install.yaml
cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/templates/namespace-post-install.yaml
manifest_staging/charts/gatekeeper/values.yaml

Allows to label extra namespace for exemption, defaulting to kube-system
Fixes #1952

helm: Label exempted namespaces

---

cmd/build/helmify/replacements.go
manifest_staging/charts/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml

Exempt Namespace label templating in the Helm chart uses a `value` field instead of `values`: `kubectl explain validatingwebhookconfiguration.webhooks.namespaceSelector.matchExpressions`
This PR fixes the templating to allow for a values override like this:
```
validatingWebhookExemptNamespacesLabels:
kubernetes.io/metadata.name:
- kube-system
- gatekeeper-system
mutatingWebhookExemptNamespacesLabels:
kubernetes.io/metadata.name:
- kube-system
- gatekeeper-system
```

fix: Fix Helm chart webhook exempt Namespace label templating

---

demo/basic/constraints/all_ns_must_have_gatekeeper.yaml

This is to fix - validation error when we apply all_ns_must_have_gatekeeper constraint
**Which issue(s) this PR fixes** **:
Fixes # fix - error validating data: ValidationError(K8sRequiredLabels.spec.parameters.labels[0]): invalid type for sh.gatekeeper.constraints.v1beta1.K8sRequiredLabels.spec.parameters.labels: got "map", expected "string"
example run of constraint-
```
$ kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/demo/basic/constraints/all_ns_must_have_gatekeeper.yaml  
agent/gatekeeper/master/demo/basic/constraints/all_ns_must_have_gatekeeper.yaml
error: error validating "https://raw.githubusercontent.com/open-policy-agent/gatekeeper/master/demo/basic/constraints/al …
```

fix: Validation error in all_ns_must_have_gatekeeper constraint

---

pkg/audit/manager.go

For https://github.com/open-policy-agent/gatekeeper/issues/2095
**What this PR does / why we need it**: Provides group and version of violating resources inside StatusViolation by copying over the group and version fields from updateListEntry.
Fixes #2095

fix: #2095 GV in constraint StatusViolation

---

pkg/audit/manager.go

make audit more fault tolerant, log error instead of skipping status update
Fixes #2120

fix: make audit more fault tolerant, log error instead of skipping update

---

.github/workflows/workflow.yaml

This uses trivy's filesystem scan [1] to scan the Gatekeeper repository
for package vulnerabilities, hardcoded secrets and config file issues
(e.g. k8se manifests or other IaC manifests).
While doing this, I also updates the trivy version that's being used in
the CI job.
[1] https://aquasecurity.github.io/trivy/v0.29.2/docs/vulnerability/scanning/filesystem/

chore: Run trivy scan on git repository and update version

---

.github/stale.yml

Signed-off-by: Sertaç Özercan <852750+sozercan@users.noreply.github.com>
updates stale bot's tag from `wontfix` to `stale`
Fixes #

chore: update stale tag

---

website/docs/mutation.md
website/versioned_docs/version-v3.7.x/mutation.md
website/versioned_docs/version-v3.8.x/mutation.md
website/versioned_docs/version-v3.9.x/mutation.md

Documents the name matcher which exists and functions but is unmentioned in the mutations documents.
N/A
Uncertain if I should also go and add this to the versioned docs. Would that be the right thing to do here?

fix: document mutations name matcher

---

cmd/build/helmify/main.go
manifest_staging/charts/gatekeeper/templates/gatekeeper-admin-podsecuritypolicy.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-poddisruptionbudget.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-manager-role-clusterrole.yaml

Signed-off-by: Michael McLeroy <michaelmcleroy@cloudfitsoftware.com>
- Removes remnant in `ClusterRole` of PodSecurityPolicy when `psp.enabled: false` is set.  Previously, only the `PodSecurityPolicy` itself was removed.
- Adds logic to default to `policy/v1` for `PodDisruptionBudget` when neither `v1` or `v1beta1` are found in the cluster (e.g. we are running `helm template`).  This will allow static analysis (e.g. linting) tools to not flag this as deprecated.
**Which issue(s) this PR fixes** 
fixes #2185, fixes #2186 

fix(helm): helm chart updates for disabling psp and default api for poddisruptionbudget

---

cmd/build/helmify/static/templates/_helpers.tpl
manifest_staging/charts/gatekeeper/templates/_helpers.tpl

Add `curl` as first argument of probeWebhook container, so it's possible to use different images which do have curl but don't have `curl` set as an entrypoint.
this is exactly what entrypoint of curlimages/curl does: it adds `curl` if first argument is not a valid command:
https://github.com/curl/curl-docker/blob/28034fa450ec24aa79cb17fe65b00eda85ae3e2c/alpine/latest/entrypoint.sh#L10-L12

fix(helm): explicitly specify curl in probeWebhook

---

Makefile

1) It adds `--rm` flag to _GEN docker commands, so they don't leave unnecessary completed containers (this is already done for lint, and probably can be done for tests – but those are a different story)
2) it changes context directory passed to `docker build` for __tooling-image from `.` to `build/tooling`: tooling image doesn't need that context at all, but `docker build` doesn't know that in advance so it still has to pass all the context to the daemon, which can takes time and is completely unnecessary. now it only passes context of a directory only containing the dockerfile itself, so it's not such an issue anymore.
these are just simple quality of development improvements to speed up tooling in docker related processes and to stop gatekeeper …

fix: Docker related Makefile improvements

---

Makefile
test/image/Dockerfile

Build a testing image and run tests with a volume mount, instead of
copying sources into a test image.
Tests work as lint and gen jobs now, which simplifes and speeds up test
development.
**Which issue(s) this PR fixes**
None I'm aware of

chore: use volume mounts for tests

---

cmd/build/helmify/static/templates/namespace-post-install.yaml
cmd/build/helmify/static/templates/namespace-post-upgrade.yaml
cmd/build/helmify/static/templates/probe-webhook-post-install.yaml
cmd/build/helmify/static/templates/upgrade-crds-hook.yaml
cmd/build/helmify/static/templates/webhook-configs-pre-delete.yaml
manifest_staging/charts/gatekeeper/templates/namespace-post-install.yaml
manifest_staging/charts/gatekeeper/templates/namespace-post-upgrade.yaml
manifest_staging/charts/gatekeeper/templates/probe-webhook-post-install.yaml
manifest_staging/charts/gatekeeper/templates/upgrade-crds-hook.yaml
manifest_staging/charts/gatekeeper/templates/webhook-configs-pre-delete.yaml

It unifies all of the hook jobs to have same labels, and to have them both on Job and Pod being created by it.
Fixes #2204

feat(helm): unify and extend hook job pod labels

---

pkg/controller/constrainttemplate/constants.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller_test.go

Currently ConstraintTemplate's `.status.created` field is set to true if there's at least one ConstraintTemplatePodStatus for it.
However, it doesn't check if ConstraintTemplatePodStatus has actually succeeded (has no errors). This PR fixes that – `.status.created` is only set to `true` if there's at least one `ConstraintTemplatePodStatus` for this template with no errors.
I've also noticed that `Err..Code` constants are used inconsistently in the constrainttemplate controller, so I've fixed that too. Please tell me if it has to be separated into a different PR.
Fixes #2053

fix: Only set ConstraintTemplate's status.created on success

---

pkg/audit/stats_reporter.go

Updates Audit Duration metric (audit_duration_seconds) with longer time period buckets.
See #2197 for more info.

chore: update audit duration buckets

---

go.mod
go.sum
vendor/modules.txt

This PR bumbs bumps github.com/emicklei/go-restful to v2.16.0. It fixes CVE CVE-2022-1996

chore: bump github.com/emicklei/go-restful from v2.15.0 to v2.16.0

---

pkg/audit/manager.go
pkg/audit/stats_reporter.go
pkg/audit/stats_reporter_test.go
website/docs/audit.md
website/docs/metrics.md
website/versioned_docs/version-v3.6.x/audit.md
website/versioned_docs/version-v3.7.x/audit.md
website/versioned_docs/version-v3.8.x/audit.md
website/versioned_docs/version-v3.9.x/audit.md

It adds a new metric to track last finishing time for audit runs, to ensure that audit runs do actually finish.
It also updates description of existing metric to note that it only shows time when audit has started, and not when audit has finished.
See #2197 for more info.

feat: add audit_last_run_end_time metric

---

pkg/gator/read_constraints.go
pkg/gator/read_constraints_test.go

While using the Gator CLI (v3.9.0) to test helm rendered k8s resources against our Gatekeeper constraints we ran into the following error: `auditing objects: adding data of GVK "/, Kind=": admission.k8s.gatekeeper.sh: invalid request object: resource  has no version`
After investigation we found out that the error was due to a input file like the following one:
```yaml
---
name: object1
attrs:
- attr1
- attr2
---
---
name: object2
labels:
- label1
- label2
```
Apparently Gator CLI attempts to parse above snippet as 3 seperate YAML documents, looking for k8s resources inside them, which won't work as the second one containing only the comment cannot be parsed into a valid k8s resource at all.
This PR suggests skipping empty k8s resources.

fix: skip empty k8s resources

---

cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/values.yaml

Signed-off-by: Chris Burke <christopher.burke@airnz.co.nz>
The helm chart default values used the incorrect case for `securityContext.capabilities.drop`.
Was:
```yaml
securityContext:
capabilities:
drop:
- all
```
Now:
```yaml
securityContext:
capabilities:
drop:
- ALL
```
Fixes #2271

fix: Change 'securityContext/capabilities/drop' from 'all' to 'ALL'.

---

cmd/gator/test/test.go
pkg/gator/test/test.go
pkg/gator/test/test_test.go
pkg/gator/test/types.go

During the refactoring of the Constraint Framework, the violating
resource was removed from the pkg/types.Result struct.
As this struct was returned in the public interface of Gatekeeper's
pkg/gator/test.Test() function, consumers of that test package were
deprived of their ability to discern which resource was causing the
violation returned to them.
This PR declares a new set of types in the `test` package that are meant
to mirror those of CF's `types` package, but that include a reference to
the violating object.
This PR also updates the gator test CLI command to use this new
interface.

feat: Return violating resource in pkg/gator/test.Test

---

.github/workflows/workflow.yaml

ci: bump trivy to 0.32.1

---

demo/agilebank/README.md
demo/basic/README.md

THIS IS A STRING CHANGE. But I think it's useful for folks like me that went straight into the `demo` folder without looking at / remembering to do the prerequisite and installation steps in the docs. I also want to help further lowering the barrier to entry here by being overly explicit about setting up a k8s cluster.
**Which issue(s) this PR fixes** 
Didn't see any issues referencing this.

style: add docs pointers from the demo folder

---

charts/gatekeeper/values.yaml
cmd/build/helmify/static/values.yaml
config/manager/manager.yaml
manifest_staging/charts/gatekeeper/values.yaml
manifest_staging/deploy/gatekeeper.yaml

Signed-off-by: Alex Pana <8968914+acpana@users.noreply.github.com>
**What this PR does / why we need it**: 
This diff removes `cpu` limits on g8r resources. Unsetting the `cpu` limit is desirable. This is because a predefined limit for a cgroup impacts the parent cgroup too. In turn, having a set cpu limit can result in weird quota exhaustions, without actually exhaustive the cpu resource. 
---
Refs: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run

perf: unset CPU limit

---

cmd/build/helmify/static/values.yaml
config/manager/manager.yaml
manifest_staging/charts/gatekeeper/values.yaml
manifest_staging/deploy/gatekeeper.yaml

Signed-off-by: Alex Pana <8968914+acpana@users.noreply.github.com>
AFAIU, there may be cases in which a container starts at the requested `memory`  but can't reach its limit. This potentially results in the workload being rescheduled. We can avoid that by setting the limit and request to the same value right out the gate.

perf: set mem request and limit to the same value

---

website/docusaurus.config.js

Updates footer slack community link of the website to easily navigate to workspace invite/sign-in page
Fixes #2334 

docs: Updating slack community ref in footer

---

.github/workflows/website.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

ci: update set-output usage

---

Makefile
cmd/gator/gator.go
gator.Dockerfile

Adds more information in output of `gator --version`
Fixes #1643 
Result:
```
gator --version
gator version 
Gator & Gatekeeper version: v3.10.0-beta.2, OPA version: 0.44.0, Framework Version v0.0.0-20221006234738-a3d297b3152f
```

chore: Adding version info for gk, opa, and frameworks in gator cmd

---

website/docs/externaldata.md
website/versioned_docs/version-v3.10.x/externaldata.md
website/versioned_docs/version-v3.7.x/externaldata.md
website/versioned_docs/version-v3.8.x/externaldata.md
website/versioned_docs/version-v3.9.x/externaldata.md

docs: add external data provider list

---

website/package.json
website/yarn.lock

reverting dependabot updates for docusaurus 2.2.0 due to:
`Error:  Error: The url is not supposed to contain a sub-path like "/gatekeeper/website/docs/". Please use the baseUrl field for sub-paths.`
This used to be a warning, let's revert until we can figure this out
https://github.com/open-policy-agent/gatekeeper/actions/runs/3363086454/jobs/5575717029
Fixes #

revert: Revert docusaurus 2.2.0

---

cmd/build/helmify/kustomize-for-helm.yaml
cmd/build/helmify/replacements.go
cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/charts/gatekeeper/values.yaml
pkg/webhook/common.go
pkg/webhook/mutation.go
pkg/webhook/namespacelabel.go
pkg/webhook/policy.go
website/docs/externaldata.md

To authenticate incoming requests from api-server to webhook
Partially addresses #1294 

chore: Authenticating api server against webhook

---

pkg/webhook/policy.go
pkg/webhook/stats_reporter.go
pkg/webhook/stats_reporter_test.go
website/docs/metrics.md

Adds additional tag under `gatekeeper_validation_request_count` to indicate if the request is dryrun
Fixes #2345 
Output after the changes for `gatekeeper_validation_request_count`:
```
gatekeeper_validation_request_count{admission_dryrun="false",admission_status="allow"} 246
gatekeeper_validation_request_count{admission_dryrun="false",admission_status="deny"} 1
gatekeeper_validation_request_count{admission_dryrun="true",admission_status="allow"} 1 …
```

chore: adding a tag to indicate dry run requests in valication request count metric

---

website/docs/externaldata.md
website/versioned_docs/version-v3.10.x/externaldata.md
website/versioned_docs/version-v3.7.x/externaldata.md
website/versioned_docs/version-v3.8.x/externaldata.md
website/versioned_docs/version-v3.9.x/externaldata.md

docs: adding doc to enable apiserver authentication in versioned docs

---

cmd/build/helmify/kustomize-for-helm.yaml
cmd/build/helmify/replacements.go
config/webhook/webhook_patch.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
manifest_staging/deploy/gatekeeper.yaml

Exclude gatekeeper-system namespace as part of matchExpressions in the webhook configs
Fixes #

fix: exclude gs namespace in matchExpressions

---

pkg/audit/manager.go

Extension to https://github.com/open-policy-agent/gatekeeper/pull/2162 to make expanded objects and audit-from-cache more fault tolerant.
Fixes #

fix: make audit fault tolerant

---

.github/workflows/workflow.yaml

Co-authored-by: sozercan <sozercan@users.noreply.github.com>
With the newly added external data tests, we are getting close to 30m for release tests
Fixes #

ci: bump release timeout to 45m (release-3.11)

---

Makefile
cmd/gator/test/gatortest_test.go

Signed-off-by: davis-haba <davishaba@google.com>
The `cmd/gator` directory was not included in our test pipeline. Currently, the only test this directory has is `cmd/gator/test/gatortest_test.go`. 
This PR adds the `cmd/gator` directory to `make native-test`. It also includes a small fix to add `evaluationmeta` to a unit test for `gator test`. 
Fixes #2482

fix: include cmd/gator in native-test and fix gatortest_test.go

---

pkg/audit/manager.go
pkg/gator/reader/read_constraints.go

Comparing with `==` will fail on wrapped errors. Use errors.Is to check for a specific error
Fixes #

chore: use errors.Is to check for a specific error

---

.github/workflows/benchmark.yaml
.github/workflows/workflow.yaml
Makefile

Releasing benchmark stats with each release and comparing benchmark data from each PR against latest released benchmark stats.
Fixes #692 

ci: Releasing benchmarks and benchmarking PR

---

pkg/audit/manager.go

This will help diagnose performance issues in audit, such as those mentioned in #2502 
Fixes #

feat: More verbose logging for audit

---

docs/RELEASE.md

Just fix syntax errors.Let the user read better

docs: fix syntax errors

---

docs/Backwards_Compatibility.md
docs/RELEASE.md
docs/Release_Management.md

fix: syntax errors in the document

---

website/docs/exempt-namespaces.md
website/versioned_docs/version-v3.10.x/exempt-namespaces.md
website/versioned_docs/version-v3.11.x/exempt-namespaces.md
website/versioned_docs/version-v3.6.x/exempt-namespaces.md
website/versioned_docs/version-v3.7.x/exempt-namespaces.md
website/versioned_docs/version-v3.8.x/exempt-namespaces.md
website/versioned_docs/version-v3.9.x/exempt-namespaces.md

Signed-off-by: Shawn Warren <shawn.w.warren@gmail.com>
**What this PR does / why we need it**: Updates documentation to call out the requirement of including a namespace in the controllerManager.exemptNamespaces list in order to add the ignore label.

chore: update docs

---

.golangci.yaml
pkg/controller/config/config_controller_test.go
pkg/controller/mutators/core/reconciler_test.go
pkg/controller/mutators/core/status.go
pkg/controller/mutators/stats_reporter_test.go
pkg/expansion/system.go
pkg/gator/expand/expand.go
pkg/gator/test/test.go
pkg/mutation/mutators/assign/assign_mutator_test.go
pkg/mutation/mutators/core/mutation_function_setter_test.go
pkg/mutation/path/parser/errors.go
pkg/mutation/schema/errors.go
pkg/webhook/policy.go

Adds errorlint checks to `golangci-lint`, standardizing the error format and error judgments
Fixes #

feat: add the errorlint check for golangci-lint

---

website/docusaurus.config.js

**What this PR does / why we need it**: To resolve error ` The url is not supposed to contain a sub-path like "/gatekeeper/website/docs/". Please use the baseUrl field for sub-paths.`
Fixes #

fix: updating url in doc config

---

.golangci.yaml
cmd/gator/expand/expand.go
main.go
pkg/controller/config/config_controller_suite_test.go

The order of package import for some files in the code is not uniform, and this pr introduces `gci` to regulate package import order
Fixes #

feat: introduce `gci` to unify the order of package import

---

.golangci.yaml

… abandoned the linter.  Replaced by unused.
Fixes #

chore: the linter `structcheck` `varcheck` and `deadcode` are deprecated (since v1.49.0)

---

build/tooling/vendormanifests.go

This was accidentally removed in #2541. 
Fixes #

fix: add vendor manifests back

---

.github/workflows/upgrade.yaml

we use the upgrade hook to update crds, shouldn't need this anymore
Fixes #
successful test: https://github.com/open-policy-agent/gatekeeper/actions/runs/4079966134/jobs/7031918524

ci(helm): remove unused kustomize step when upgrading

---

website/docs/expansion.md
website/versioned_docs/version-v3.10.x/expansion.md
website/versioned_docs/version-v3.11.x/expansion.md

docs: fix expansion yaml example

---

test/image/Dockerfile

This pins the golang image (used for test tooling) to a digest that contains Go 1.19.5 but without the git update to unblock pr tests
see #2569 for more details (keeping this open so we can use that for a longer-term fix)
Fixes #

ci: pin golang image to unblock ci

---

Makefile

moving from k8s.gcr.io to registry.k8s.io since images will be frozen in GCR https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
Fixes #

ci: move k8s.gcr.io to registry.k8s.io

---

.golangci.yaml
pkg/metrics/registry/registry.go

```shell
➜  gatekeeper git:(chore/unconvert) golangci-lint run -c .golangci.yaml
pkg/metrics/registry/registry.go:63:37: unnecessary conversion (unconvert)
contents = append(contents, string(k))
^
➜  gatekeeper git:(chore/unconvert) ✗ golangci-lint run -c .golangci.yaml
➜  gatekeeper git:(chore/unconvert) ✗ 
```
Fixes #

feat: add unconvert check for golang-lint

---

apis/status/v1beta1/constraintpodstatus_types_test.go
pkg/readiness/ready_tracker_test.go

```shell
➜  gatekeeper git:(master) golangci-lint run -c .golangci.yaml
apis/status/v1beta1/constraintpodstatus_types_test.go:4:2: "strings" imported but not used (typecheck)
"strings"
^
pkg/readiness/ready_tracker_test.go:574:21: invalid operation: cannot compare tc.tracker != nil (operator != not defined on untyped nil) (typecheck)
if tc.tracker != nil {
^
```
Fixes #

chore: modify the typecheck as prompted

---

pkg/mutation/mutators/assignmeta/assignmeta_mutator_test.go
pkg/webhook/policy_benchmark_test.go
pkg/webhook/policy_test.go

Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
Clean up repeated package import
Fixes #

chore: clean up repeated package import

---

cmd/build/helmify/static/templates/namespace-post-install.yaml
cmd/build/helmify/static/templates/namespace-post-upgrade.yaml
cmd/build/helmify/static/templates/webhook-configs-pre-delete.yaml
manifest_staging/charts/gatekeeper/templates/namespace-post-install.yaml
manifest_staging/charts/gatekeeper/templates/namespace-post-upgrade.yaml
manifest_staging/charts/gatekeeper/templates/webhook-configs-pre-delete.yaml

A few static templates for the Helm chart are missing a namespace when rendered using `helm template`, causing failure when applied this way with a non-default namespace:
```shell
helm template gatekeeper gatekeeper/gatekeeper -n kube-system | kubectl apply -f -
```
```shell
kubectl get jobs
NAME                                         COMPLETIONS   DURATION   AGE
gatekeeper-update-namespace-label            0/1           39s        39s
kubectl get serviceaccounts
NAME                                  SECRETS   AGE
gatekeeper-update-namespace-label     0         87s
kubectl get clusterrolebinding gatekeeper-update-namespace-label -o yaml
...
subjects:
- kind: ServiceAccount
name: gatekeeper-update-namespace-label
namespace: kube-system
kubectl …
```

fix: add missing namespace to static Helm templates

---

pkg/mutation/mutators/assign/assign_mutator_test.go
pkg/mutation/mutators/assignmeta/assignmeta_mutator_test.go
pkg/mutation/mutators/modifyset/modify_set_mutator.go
pkg/mutation/mutators/modifyset/modify_set_mutator_benchmark_test.go
pkg/mutation/mutators/modifyset/modify_set_mutator_test.go

Fixes https://github.com/open-policy-agent/gatekeeper/issues/2574

fix: handle empty spec for modifyset

---

pkg/gator/reader/filereader.go
test/gator/test/test.bats

fixes https://github.com/open-policy-agent/gatekeeper/issues/2582

fix: piping input in gator

---

.github/workflows/workflow.yaml
Tiltfile

ci: remove k8s 1.23 from matrix

---

cmd/gator/test/gatortest_test.go
pkg/gator/test/test_test.go

Re working some of these to be less brittle. It's going to help any time we make changes to the `Result` type in CF.
Signed-off-by: Alex Pana <8968914+acpana@users.noreply.github.com>

test: use custom filter to make tests less brittle

---

.github/workflows/license-lint.yaml

Upgrades checkout action to v3
Fixes https://github.com/open-policy-agent/gatekeeper/issues/2605
None

ci: Upgrade checkout action to v3

---

website/docs/mutation.md

update a mention of `applyTo` to call out that `applyTo` is a required field for `AssignImage`

docs: update applyTo description to mention AssignImage

---

.github/workflows/release.yaml

This fixes gator cli builds during release and it should mark the job as failed if build fails
Fixes #2656
Will need to be cherry picked to release-3.12 branch after merged

ci: fix gator cli build

---

.github/workflows/release.yaml

Co-authored-by: sozercan <sozercan@users.noreply.github.com>**What this PR does / why we need it**:
Fixes #

ci: cherry pick #2657 to release-3.12

---

main.go

If manager exits without an error, then it's error channel is never closed, which causes blockingLoop to hang indefinitely.
This was papered over by Kubernetes' termination grace period behavior:
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination
Fixes #

fix: eliminate deadlock-on-exit

---

pkg/webhook/health_check.go

cherry pick https://github.com/open-policy-agent/gatekeeper/issues/2690 to release-3.11 branch

fix: [release-3.11] cherry pick #2690

---

website/docusaurus.config.js

The parenthesis at the end of the link is invalid, meaning the meeting is a dead link.
Fixes #

docs: Fix meeting link in website bottom bar

---

index.html

This removes the redirect to `/docs` on the website so it lands on the homepage by default

docs: remove old redirect on index.html

---

docs/design/README.md

**What this PR does / why we need it**: Adding design doc for pubsub to appropriate place in gatekeeper
Fixes #2555 

docs: Adding pubsub design to docs

---

Makefile
crd.Dockerfile

Migrate from https://storage.googleapis.com/kubernetes-release to https://dl.k8s.io
https://github.com/kubernetes/k8s.io/issues/2396
Fixes #

chore: migrate to dl.k8s.io storage

---

Makefile

fixes https://github.com/open-policy-agent/gatekeeper/issues/2825
After changes:
```bash
$ make gator && file ./bin/gator
./bin/gator: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=RCa34m4KxNkndGrvlkby/dC7Eydt9Mi5d0rOW8JKV/kC4hP7hRpgDaw8-aOUy2/J8nfYbCPMRkaGM8wTFgV, with debug_info, not stripped
```
Notice `statically linked`. Before changes:
```bash
$ make gator && file ./bin/gator
./bin/gator: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=6O50_OD8mTvb3GOw2xK7/YBG9hxjCyAmV2a510vXp/M1QQS4iPBdcfFKct_6Ff/v7D7mRXcr-XX9wI2Ei72, with debug_info, not stripped
```

fix: statically link gator binary

---

apis/config/v1alpha1/config_types.go
apis/config/v1alpha1/zz_generated.deepcopy.go
pkg/controller/config/config_controller_test.go
pkg/controller/config/process/excluder.go
pkg/controller/config/process/excluder_test.go
pkg/mutation/match/match_test.go
pkg/mutation/match/match_types.go
pkg/mutation/match/zz_generated.deepcopy.go
pkg/mutation/mutators/conversion_test.go
pkg/syncutil/cachemanager/cachemanager_test.go
pkg/target/target_test.go
pkg/webhook/policy_test.go
pkg/wildcard/wildcard.go
pkg/wildcard/wildcard_test.go

We ran into an issue when updating our product to controller-runtime 0.15. We tried gatekeeper v3.13.0-beta.1 and ended up with
```
github.com/open-policy-agent/gatekeeper/v3/pkg/util
../../github.com/open-policy-agent/gatekeeper/pkg/util/pack.go:44:9: cannot use func(obj client.Object) []reconcile.Request {…} (value of type func(obj client.Object) []reconcile.Request) as handler.MapFunc value in return statement
../../github.com/open-policy-agent/gatekeeper/pkg/util/pack.go:70:9: cannot use func(obj client.Object) []reconcile.Request {…} (value of type func(obj client.Object) []reconcile.Request) as handler.MapFunc value in return statement
../../github.com/open-policy-agent/gatekeeper/pkg/util/pack.go:75:13: not enough arguments in call to mf
have …
```

refactor: move util.Wildcard into its own package

---

website/src/pages/styles.module.css

Links are not readable in dark mode
Fixes #2778
**Home page**

docs: fix link coloring issue in dark mode

---

go.mod
go.sum
vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go
vendor/modules.txt

bumps cert controller to include https://github.com/open-policy-agent/cert-controller/pull/81
That should fix https://github.com/open-policy-agent/gatekeeper/issues/2477 .

chore: update cert-controller

---

docs/Release_Management.md

Update docs to reflect an every 3 months release cadence that we've been following for a bit now
Fixes #2905 

docs: update release cadence to three months

---

website/docs/metrics.md

`status` tag for the expansion metric was added https://github.com/open-policy-agent/gatekeeper/commit/7c519b47ad37b577ff1eec433b3691c4b53096b2#diff-f0449d86125583f31ed617705320bfdea120325b261a3eb252431dd691340b04R28 and it will only be available as part of the 3.13.0 release. so no need to add to older docs. 
Fixes #

docs: Add status tag for expansion metric

---

Dockerfile
Makefile
Tiltfile
cmd/gator/gator.go
gator.Dockerfile
main.go
pkg/version/version.go

- Uses buildinfo to bake in opa and frameworks version so these will be visible in gator installed from homebrew. Unfortunately, we cannot do this for tag since Go doesn't support that (since tags are mutable?), so we have to keep `LDFLAGS` for version.
- Printing OPA version inside manager too since we are getting questions about this
- Fixes version bug that we missed to add /v3
Fixes #2534 

refactor: use buildinfo to get opa and frameworks version

---

website/docs/expansion.md
website/versioned_docs/version-v3.13.x/expansion.md

**What this PR does / why we need it**: Right now, quotes are visible on the website in the title instead of being rendered and looking appropriate.
Fixes #

docs: removing quotes from the title in expansion template doc

---

pkg/readiness/object_tracker.go
pkg/readiness/object_tracker_test.go
pkg/readiness/tracker_map.go

The following sync config would cause readiness tracker to hang:
```yaml
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
name: config
namespace: gatekeeper-system
spec:
sync:
syncOnly:
- group: ""
kind: Namespace
version: v1
- group: networking.k8s.io
kind: NetworkPolicy
version: v1
- group: networking.k8s.io
kind: NetworkPolicy
version: v1
```
this PR fixes that.
Fixes #

fix: Remove readiness tracker deadlock caused by duplicate syncs

---

website/docs/externaldata.md
website/versioned_docs/version-v3.13.x/externaldata.md

docs: adds documentation about provider response caching

---

pkg/audit/manager.go

Update `audit-from-cache` flag description to clearly let the users know about auditing from synced resources from the internal cache
Fixes https://github.com/open-policy-agent/gatekeeper/issues/2948

fix(audit): Update audit-from-cache flag description

---

main.go
pkg/controller/config/config_controller.go
pkg/controller/config/config_controller_test.go
pkg/controller/constraint/constraint_controller.go
pkg/controller/constraintstatus/constraintstatus_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller.go
pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller_test.go
pkg/controller/controller.go
pkg/controller/expansion/expansion_controller.go
pkg/controller/expansionstatus/expansionstatus_controller.go
pkg/controller/externaldata/externaldata_controller.go
pkg/controller/externaldata/externaldata_controller_test.go
pkg/controller/mutators/instances/mutator_controllers.go
pkg/controller/mutatorstatus/mutatorstatus_controller.go
pkg/controller/pubsub/pubsub_config_controller.go
pkg/readiness/ready_tracker_test.go

Following up on punted work items from: https://github.com/open-policy-agent/gatekeeper/pull/2852
* simplifies the `Injector` interface for controllers; many controllers don't implement the interface funcs
* renames references to (data) client

refactor: adder interface, rename data client

---

cmd/gator/test/gatortest_test.go
cmd/gator/test/test.go

When running `gator test -f="directory/"`, it doesn't tell which file is violating the constraint. This may be fine for a small set of manifests but becomes annoying when validating large sets.
This is my first contribution here. The attempt I'm making aims to have a small footprint but that may be the completely wrong approach for this.

feat(gator): print object name on test output

---

main.go
website/docs/externaldata.md
website/versioned_docs/version-v3.13.x/externaldata.md

Disables provider response cache when TTL is set to 0
Fixes https://github.com/open-policy-agent/gatekeeper/issues/3024

feat: disables provider response cache when TTL is set to 0

---

demo/k8s-validating-admission-policy/README.md
main.go
pkg/webhook/policy.go
website/docs/constrainttemplates.md
website/docs/validating-admission-policy.md
website/versioned_docs/version-v3.13.x/constrainttemplates.md
website/versioned_docs/version-v3.13.x/validating-admission-policy.md

**What this PR does / why we need it**: Introducing flag to validate rego in constraint template. 
Fixes #3008 
I am not erroring out if `experimental-enable-k8s-native-validation` and `validate-template-rego` both are enabled at the same time as we discussed. Instead, the behavior is if `validate-template-rego` is enabled then any templates with cel will be rejected with the error "invalid rego", but the templates that exist in the cluster already with cel will still work (feels like less breaking change with this approach). Additionally, updates on cel templates will throw an "invalid …

fix: adding flag to validate rego for templates

---

.github/workflows/release.yaml

release is blocked due to running out of disk space https://github.com/open-policy-agent/gatekeeper/actions/runs/6423263625
seems like GHA runners starts with a 78% full disk 🤷‍♂️
removing [cached images](https://github.com/actions/runner-images/blob/releases/ubuntu22/20231001/images/linux/Ubuntu2204-Readme.md#cached-docker-images) (~6gigs) that we don't use 
Fixes #

chore: cleanup disk usage before release

---

pkg/logging/logging.go

Verbosity log levels (V level) are additive so starting at 2 is actually a higher level than `Debug`. So in effect, today, if users use `log-level=DEBUG` any log line that uses `loggging.Debug` as its V level will not see the line since we don't have a control for higher verbosity (>1) yet.
Not sure why it was 2 to begin with but I think it may have been missed on the original PR that introduced it https://github.com/open-policy-agent/gatekeeper/pull/482.

fix: use log level 1 for debug

---

pkg/cachemanager/aggregator/aggregator.go
pkg/cachemanager/aggregator/aggregator_test.go

Small enhancement to have the aggregator not ingest any empty gvks.

fix:enh: protect agg against empty gvks

---

.github/workflows/pre-release.yaml
.github/workflows/release.yaml

`registry.k8s.io/kubectl:v1.28.2` does not include 32-bit arm/v7 kubectl, which blocks us from building gatekeeper-crds image for arm/v7
Also fixes a bug in the pre-release CI where we omitted `\`, this should have been caught there
Fixes #
This is blocking v3.14.0 release so needs to be cherry picked there after merge

ci: drop arm/v7 builds for crd image

---

.github/workflows/release-pr.yaml

**What this PR does / why we need it**: Sign off PRs raised by release pr action to eliminate the need of manually signing it for DCO.
Fixes #3036 

fix: auto signing PR for dco

---

pkg/audit/manager.go
pkg/audit/manager_test.go
pkg/fakes/fixtures.go

fix: ns exclusion audit from cache (#3129) cherry-pick for 3.14

---

pkg/webhook/common.go
pkg/webhook/policy.go
pkg/webhook/policy_test.go

Follow up to https://github.com/open-policy-agent/gatekeeper/pull/3094 -- only check name len if the resources is a gatekepeer resource

fix: only validate gk res

---

pkg/audit/manager.go

fixes https://github.com/open-policy-agent/gatekeeper/issues/3171
this was a dormant panic it seems that never got hit before since the log level was never exercised prior to changing the DebugLevel to 1.

fix: log panic in am

---

pkg/audit/manager.go

Cherry pick of https://github.com/open-policy-agent/gatekeeper/pull/3174 for 3.14

fix: log panic in am (#3174) cherry-pick for 3.14

---

website/versioned_docs/version-v3.14.x/install.md

Typo perhaps.
I encountered an error as below.
```
ubuntu@ubuntu-playground:~/gatekeeper$ export DESTINATION_GATEKEEPER_IMAGE=opa-test.sakuracr.jp/gatekeeper
ubuntu@ubuntu-playground:~/gatekeeper$ echo $DESTINATION_GATEKEEPER_IMAGE
opa-test.sakuracr.jp/gatekeeper
ubuntu@ubuntu-playground:~/gatekeeper$ echo $DESTINATION_GATEKEEPER_DOCKER_IMAGE
ubuntu@ubuntu-playground:~/gatekeeper$ make docker-buildx REPOSITORY=$DESTINATION_GATEKEEPER_DOCKER_IMAGE OUTPUT_TYPE=type=registry
if ! docker buildx ls | grep -q container-builder; then\
docker buildx create --name container-builder --use --bootstrap;\
docker buildx inspect;\
fi
docker buildx build \
\
--build-arg LDFLAGS="-X github.com/open-policy-agent/gatekeeper/v3/pkg/version.Version=v3.15.0-beta.0" \ …
```

docs: Update install.md

---

website/docs/install.md
website/versioned_docs/version-v3.10.x/install.md
website/versioned_docs/version-v3.11.x/install.md
website/versioned_docs/version-v3.12.x/install.md
website/versioned_docs/version-v3.13.x/install.md
website/versioned_docs/version-v3.14.x/install.md
website/versioned_docs/version-v3.6.x/install.md
website/versioned_docs/version-v3.7.x/install.md
website/versioned_docs/version-v3.8.x/install.md
website/versioned_docs/version-v3.9.x/install.md

docs: update repo env var

---

website/docs/help.md
website/versioned_docs/version-v3.14.x/help.md

**What this PR does / why we need it**: Issue #66 mentions needing docs on how to contribute templates upstream. This is documented in the library README, so this PR provides a link from the Gatekeeper 'contributing' docs to those docs.

docs: add docs on how to contribute templates

---

pkg/audit/manager.go

Debug log is causing panic due to odd number of key/value passed.
Fixes #

fix: fixing panic in debug log

---

website/docs/howto.md
website/docs/input.md
website/sidebars.js
website/versioned_docs/version-v3.14.x/howto.md
website/versioned_docs/version-v3.14.x/input.md
website/versioned_sidebars/version-v3.14.x-sidebars.json

**What this PR does / why we need it**: Part of the docs requested in #66. Gives users documentation on the structure of admission requests.

docs: add request input struct

---

demo/k8s-validating-admission-policy/README.md
main.go
pkg/webhook/policy.go
website/docs/constrainttemplates.md
website/docs/validating-admission-policy.md

Removing the flag to validate rego in constraint template.
Fixes #3027

fix: Remove validation of constraint template rego

---

.github/workflows/upgrade.yaml
.github/workflows/workflow.yaml
test/bats/tests/mutations/mutate_svc.yaml

drops eol 1.25, adds 1.29
Fixes #

ci: bump k8s matrix

---

Makefile
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go

fix: update unit test for vap generation; add custom assets for envtest

---

cmd/build/helmify/main.go
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml

Signed-off-by: James Bruce <james.bruce@ba.com>
Co-authored-by: Rita Zhang <rita.z.zhang@gmail.com>
(cherry picked from commit 902a1b4f7fd97d6ee59a7078fa28485f4e1a018f)
Details in https://github.com/open-policy-agent/gatekeeper/pull/3240

feat: Update audit and controller manager with pod labels (#3240) (cherry pick)

---

pkg/audit/stats_reporter.go
pkg/controller/constrainttemplate/stats_reporter.go
pkg/controller/mutators/stats_reporter.go
pkg/syncutil/stats_reporter.go
pkg/webhook/stats_reporter.go

**What this PR does / why we need it**: Order of registering views in otel metrics was no in orientation and is causing views to used default configurations instead of custom.
Fixes #3303

fix: fixing metrics views

---

go.mod
go.sum
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/pipe.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/testsync.go
vendor/golang.org/x/net/http2/transport.go
vendor/modules.txt

govulncheck is failing because of GO-2024-2687
https://pkg.go.dev/vuln/GO-2024-2687
Fixes #

chore: fix GO-2024-2687

---

website/docs/metrics.md
website/versioned_docs/version-v3.15.x/metrics.md

docs: correcting metrics names

---

demo/basic/good/good_ns.yaml
demo/basic/good/no_dupe_ns.yaml
demo/k8s-validating-admission-policy/README.md
demo/k8s-validating-admission-policy/bad_namespace.yaml
demo/k8s-validating-admission-policy/demo.sh
demo/k8s-validating-admission-policy/k8srequiredlabels_template.yaml
demo/k8s-validating-admission-policy/k8srequiredlabels_template_usevap.yaml
demo/k8s-validating-admission-policy/owner_must_be_provided.yaml
website/docs/validating-admission-policy.md

docs: add vap generation doc and demo

---

Dockerfile
gator.Dockerfile
test/externaldata/dummy-provider/Dockerfile
test/pubsub/fake-subscriber/Dockerfile

chore: bump BASEIMAGE from static to static-debian12

---

Makefile

ci: fix test storage url

---

cmd/build/helmify/replacements.go
manifest_staging/charts/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml

fix: adding pod subresources in mutation rules

---

cmd/build/helmify/kustomize-for-helm.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml

Noticed when testing the oss chart with Helm, the cel enablement flags were not available on Audit
Fixes #

fix: include cel flags on audit deployment

---

pkg/pubsub/dapr/fake_dapr_client.go

updating dapr fake client to use non deprecated function for initializing clients. Should fix ci-error on #3446 
Fixes #

chore: fixing deprecating function in dapr fake test client

---

cmd/build/helmify/kustomize-for-helm.yaml
cmd/build/helmify/replacements.go
cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
manifest_staging/charts/gatekeeper/values.yaml

**What this PR does / why we need it**: Based on this comment https://github.com/open-policy-agent/gatekeeper/pull/3476#discussion_r1710406145, we should avoid setting `alpha` flags through helm. This PR only sets `default-create-vap-for-templates` and `default-create-vap-binding-for-constraints` when its explicitly passed in values.
Fixes #

chore: Removing setting alpha flags for vap/vapb generation unless explicitly set through helm

---

pkg/controller/constraint/constraint_controller.go
pkg/controller/constraint/constraint_controller_test.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go

(cherry picked from commit 4eb7dcd9f27d1454db8caf987114ca47748fbbcb)
Fixes #

fix: fixing error reporting for templates without CEL, cherry-pick (#3493)

---

demo/k8s-validating-admission-policy/README.md
demo/k8s-validating-admission-policy/demo.sh
demo/k8s-validating-admission-policy/k8srequiredlabels_template.yaml
demo/k8s-validating-admission-policy/k8srequiredlabels_template_usevap.yaml
website/docs/validating-admission-policy.md

docs: update vap doc and demo

---

cmd/build/helmify/main.go
manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-poddisruptionbudget.yaml

Signed-off-by: Thomas Berreis <thomas@berreis.de>
Co-authored-by: Jaydipkumar Arvindbhai Gabani <gabanijaydip@gmail.com>
(cherry picked from commit 3f457329ebacdb248f2ab2135b188e530362bcf0)
Fixes #

fix: liniting error in gatekeeper-controller-manager-poddisruptionbudget.yaml, cherry-pick (#3519)

---

cmd/build/helmify/static/values.yaml
manifest_staging/charts/gatekeeper/values.yaml

When setting custom ingress rules for the NetworkPolicy via `controllerManager.networkPolicy.ingress`, helm spits out a warning, because the default value is set to `{ }` instead of an array.
Example Values:
```yaml
controllerManager:
networkPolicy:
enabled: true
ingress:
- from:
- ipBlock:
cidr: 0.0.0.0/0
```
Helm Warning:
```
coalesce.go:286: warning: cannot overwrite table with non table for gatekeeper.controllerManager.networkPolicy.ingress (map[])
```
This fixes it by setting the default value to an empty array.
Fixes #

fix: helm warning when setting NetworkPolicy ingress rule(s)

---

pkg/gator/errors.go
pkg/gator/fixtures/fixtures.go
pkg/gator/reader/read_resources.go
pkg/gator/verify/runner.go
pkg/gator/verify/runner_test.go
pkg/gator/verify/suite.go
test/gator/verify/allow_expansion.yaml
test/gator/verify/deny_expansion.yaml
test/gator/verify/expansion.yaml
test/gator/verify/suite.yaml
website/docs/gator.md

It allows for expansion in gator verify. 
Fixes #3432

feat: support expansion in gator verify

---

Makefile

fixes ghcr image push since DH and GH org names are slightly different (`openpolicyagent` vs `open-policy-agent`)
Fixes #3697 

ci: fix ghcr push

---

Makefile

- rearranged makefile to be consistent
- fixed gator image name
Fixes #

ci: fix gator image for ghcr

---

.github/workflows/check-manifest.yaml
.github/workflows/license-lint.yaml
.github/workflows/release-pr.yaml
.github/workflows/release.yaml
.github/workflows/scan-vulns.yaml
.github/workflows/test-gator.yaml
.github/workflows/unit-test.yaml
.github/workflows/workflow.yaml
.golangci.yaml
Tiltfile

build images are already using 1.23, matching ci to same version
Fixes #

ci: bump to go 1.23 in gha

---

pkg/controller/constrainttemplate/constrainttemplate_controller.go
test/bats/helpers.bash
test/bats/test.bats

**What this PR does / why we need it**: Since we are deleting VAPB when constraint is being deleted, this test should not be needed anymore.
Fixes #3713 

chore: removing wait of vapb deletion

---

pkg/controller/constrainttemplate/constrainttemplate_controller.go
test/bats/helpers.bash
test/bats/test.bats

(cherry picked from commit 9a85a21fd3c2f5821f9c6f3c35457a448b594d1f)
Fixes #

chore: removing wait of vapb deletion, cherry-pick (#3718)

---

pkg/controller/constraint/constraint_controller.go
pkg/controller/constraint/constraint_controller_test.go

fix: fixing nil pointer error when converting VAPB from v1beta1 to v1

---

pkg/controller/constraint/constraint_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller.go
pkg/controller/constrainttemplate/constrainttemplate_controller_test.go

chore: adding annotation to generate VAPB right away once the waiting window is over to protect against clock skews

---

pkg/webhook/common.go
pkg/webhook/policy_test.go

**Which issue(s) this PR fixes**
#3743 
I think that substituting req.Object for req.OldObject is the simplest solution, and it prevents us from modifying the logic in https://github.com/open-policy-agent/gatekeeper/blob/v3.18.0/pkg/webhook/policy.go#L172.
let me know if you want me to do it in another way.

fix: parse namespace from oldObject when processing a DELETE operation

---

.github/workflows/release.yaml

To avoid running out of space while building and releasing artifacts - https://github.com/open-policy-agent/gatekeeper/actions/runs/14099177360/attempts/2.
Fixes #

ci: cleaning up disk in release workflow to avoid running out of space

---

main.go

Currently readiness probe is executed before webhooks are ready, resulting in a failed event even if the webhooks are ready afterwards.
Fixes #4055 

fix: removing readinessprobe for webhook at start of the pod

---

website/docs/gator.md
website/versioned_docs/version-v3.11.x/gator.md
website/versioned_docs/version-v3.12.x/gator.md
website/versioned_docs/version-v3.13.x/gator.md
website/versioned_docs/version-v3.14.x/gator.md
website/versioned_docs/version-v3.15.x/gator.md
website/versioned_docs/version-v3.16.x/gator.md
website/versioned_docs/version-v3.17.x/gator.md
website/versioned_docs/version-v3.18.x/gator.md
website/versioned_docs/version-v3.19.x/gator.md
website/versioned_docs/version-v3.20.x/gator.md

**What this PR does / why we need it**: inexperienced developers who are new to gatekeeper, may want to install ORAS, and having a working link helps encourage them and builds a community for gatekeeper
(didn't raise any issues as it's just a url update)

docs: update link to install ORAS CLI
