Gopkg.lock, Makefile, README.md, cmd/main.go, deploy/kubernetes-policy-controller.kubeconfig, deploy/kubernetes-policy-controller.yaml, docs/design/design.md, images/kubernetes-policy-controller/.gitignore, pkg/opa/opa.go, pkg/policies/types/types.go, pkg/server/server.go, pkg/server/server_test.go, policy/authorization/crds.rego, policy/authorization/kube-system-exec.rego, policy/authorization/psp.rego, policy/authorization/storageclasses.rego, policy/authorization/util.rego, policy/authorization/webhooks.rego, policy/kubernetes/matches.rego
https://github.com/Azure/kubernetes-policy-controller/issues/22
=> added authorize endpoint

LICENSE
Updating the LICENSE to Apache v2
For more details refer to https://github.com/open-policy-agent/opa/issues/1093
=> Updating the LICENSE to Apache v2

CODE_OF_CONDUCT.md, README.md
Closes #38 
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>
=> Clean up README for the CNCF contribution

README.md
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> Update README with information to get involved

README.md
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> Add notice about upcoming changes to KPC policies

deploy/gatekeeper.yaml
As discussed in #53 this fixes the gateway container port.
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
/cc @tsandall @rite2nikhil @maxsmythe
=> fix(deploy): #53 fixes gatekeeper containerPort

.travis.yml, Dockerfile_ci, Makefile, build/get-build-commit.sh, build/get-build-hostname.sh, build/get-build-timestamp.sh
Initial CI integration that incorporates Travis CI testing
Task List
[x] Create image repository on [quay.io/open-policy-agent/gatekeeper](https:///quay.io/repository/open-policy-agent/gatekeeper)
[x] Pushes image to 
[x] Tags image as `dev` for any commit to master
=> Initial CI integration

.travis.yml, README.md
Adds additional resilience to dependency retrieval and app badges for Travis and Quay
=> CI enhancements

pkg/webhook/policy.go
Fixes #72: fixes gatekeeper service selector
/cc @tsandall @rite2nikhil @maxsmythe
=> fix(deploy):#72 fixes gatekeeper service selector

pkg/webhook/policy.go
Adding `enable-manual-deploy` flag to allow users to manually create webhook related objects, such as secret, service, and mutatingwebhookconfiguration, thus allowing more customizations. The `enable-manual-deploy` flag is default to `false`, which relies on kubebuilder to create all these objects in the cluster in the predefined namespace.
@maxsmythe @rite2nikhil
=> feat(deploy): add manual deploy option

pkg/policies/types/types.go
Fixes #76 
cc @rite2nikhil @maxsmythe
=> Fix audit returning empty resource

Makefile
Signed-off-by: Torin Sandall <torinsandall@gmail.com>
=> Bumping version to 2.1.0

pkg/target/regolib/src.rego, pkg/target/regolib/util_test.rego, pkg/target/target.go
To be merged after the data sync stuff is merged.
=> Fix audit target

demo/good_ns.yaml, pkg/controller/config/config_controller.go, pkg/target/regolib/src.rego, pkg/target/target.go
=> Clean up aesthetic code nits

config/rbac/rbac_role.yaml, deploy/gatekeeper-constraint.yaml
Add simple deploy yaml for kicking the tires and remove duplicate things in rbac_role.yaml
=> Add a deployment yaml to deploy all gatekeeper things

README.md
=> update README with simple deploy

config/manager/manager.yaml, demo/all_ns_gatekeeper_label_unique.yaml, demo/demo.sh, demo/k8suniquelabels_template.yaml, demo/no_dupe_ns.yaml, demo/no_dupe_ns_2.yaml, third_party/demo-magic/.editorconfig, third_party/demo-magic/.gitignore, third_party/demo-magic/README.md, third_party/demo-magic/demo-magic.sh, third_party/demo-magic/license.txt, third_party/demo-magic/samples/demo-template.sh
=> Add a demo script

Makefile, config/kustomization.yaml, config/manager_image_patch.yaml
=> fix deploy issue with kustomize

pkg/controller/constraint/constraint_controller.go, pkg/controller/constrainttemplate/constrainttemplate_controller.go, pkg/watch/manager.go
=> Fix deadlock due to watch manager restart errors

Makefile, deploy/gatekeeper-constraint.yaml
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> bump version v3.0.1

deploy/gatekeeper-constraint.yaml
=> fix ValidatingWebhookConfiguration name

README.md
=> Add audit to README

pkg/webhook/policy.go
Per https://github.com/open-policy-agent/gatekeeper/issues/122
=> Report constraint name in rejection message.

Gopkg.lock, vendor/github.com/open-policy-agent/frameworks/constraint/README.md, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/crd_helpers.go
This integrates the fix addressing https://github.com/open-policy-agent/gatekeeper/issues/123
=> Upgrade Constraint Framework

README.md
=> Add documentation for running traces

Makefile
=> bump version

Makefile, deploy/gatekeeper.yaml
=> bump version for deployment

deploy/gatekeeper.yaml
Signed-off-by: Craig Hooper <craig.hooper@gmail.com>
=> Fix bad indent in deploy/gatekeeper.yaml

Gopkg.lock, pkg/target/target.go, vendor/github.com/open-policy-agent/frameworks/constraint/Gopkg.lock, vendor/github.com/open-policy-agent/frameworks/constraint/config/crds/templates_v1alpha1_constrainttemplate.yaml, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/client.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/client_test.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/e2e_tests.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/regolib/src.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/test_handler.go
Fixes #153 
Pending merging of https://github.com/open-policy-agent/frameworks/pull/26 and vendoring of the latest constraint framework
=> handle namespaceselector failure

Makefile
=> bump alpha release

Makefile, deploy/gatekeeper.yaml
=> Bump image tag in deployment

deploy/gatekeeper.yaml, pkg/webhook/policy.go, pkg/webhook/policy_mutating.go, pkg/webhook/server.go, pkg/webhook/webhook.go
Verified that when GK was deployed on K8s, the log messages were printed
as expected.
Signed-off-by: Jessica de Leeuw <jessicadl@google.com>
=> Add a mutating webhook to GK.

README.md, demo/agilebank/remediation/k8sbannedimagetags_template.yaml, demo/basic/bad/bad_template.yaml, example/constraints/all_pod_must_have_gatekeeper_namespaceselector.yaml, example/templates/k8srequiredlabels_template.yaml
=> Update apiversion, input in yaml

pkg/controller/config/config_controller.go, pkg/util/pod_info.go, pkg/webhook/policy.go
=> Make gatekeeper namespace-agnostic

Makefile
=> Always check for a tag update before building container

pkg/controller/mutationtemplate/mutationtemplate_controller.go
Changes in the spec fields below OpenAPIV3Schema in a MutationTemplate (i.e. the fields that define the Mutation CRD) also updates that MutationTemplate's Mutation CRD without having to create and delete it and its Mutation CRs. Compiles according to `make test`.
How to test the updating feature:
Create a MutationTemplate .yaml and kubectl apply it (i.e. create an MT in your cluster)
Observe the parameters your Mutation CRD has using `kubectl describe crds/yourmutationname.mutations.gatekeeper.sh`
Use `kubectl edit mutationtemplates/yourmutationname` or edit `yourmutationtemplate.yaml` and add a field: 
```
test:
type: integer
```
Then, quit the `kubectl edit` or  `kubectl apply -f yourmutationtemplate.yaml`.
`kubectl describe crds/yourmutationname.mutations.gatekeeper.sh` should now …
=> Updating MutationTemplate CRs also updates Mutation CRDs

pkg/controller/constraint/constraint_controller.go
=> Fix handling of unrecognized constraints on deletion

Makefile, docs/RELEASE.md
=> Add docs and update script for make release

library/pod-security-policy/allow-privilege-escalation/constraint.yaml, library/pod-security-policy/allow-privilege-escalation/template.yaml, library/pod-security-policy/flexvolume-drivers/constraint.yaml, library/pod-security-policy/flexvolume-drivers/template.yaml, library/pod-security-policy/fsgroup/constraint.yaml, library/pod-security-policy/fsgroup/template.yaml, library/pod-security-policy/host-filesystem/constraint.yaml, library/pod-security-policy/host-filesystem/template.yaml, library/pod-security-policy/host-namespaces/constraint.yaml, library/pod-security-policy/host-namespaces/template.yaml, library/pod-security-policy/host-network-ports/constraint.yaml, library/pod-security-policy/host-network-ports/template.yaml, library/pod-security-policy/privileged-containers/constraint.yaml, library/pod-security-policy/privileged-containers/template.yaml, library/pod-security-policy/proc-mount/constraint.yaml, library/pod-security-policy/proc-mount/template.yaml, library/pod-security-policy/read-only-root-filesystem/constraint.yaml, library/pod-security-policy/read-only-root-filesystem/template.yaml, library/pod-security-policy/volumes/constraint.yaml, library/pod-security-policy/volumes/template.yaml
=> Update library templates and constraints version

Gopkg.lock, pkg/audit/controller.go, pkg/audit/manager.go, pkg/controller/config/config_controller.go, pkg/controller/constraint/constraint_controller.go, pkg/controller/constrainttemplate/constrainttemplate_controller.go, pkg/controller/controller.go, pkg/controller/sync/sync_controller.go, pkg/webhook/policy.go, pkg/webhook/policy_test.go, pkg/webhook/webhook.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/backend.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/client.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/client_test.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/e2e_tests.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/client/probe_client.go
This makes the CF client more go-like
=> Use struct literal instead of an interface for the client

pkg/target/regolib/src.rego, pkg/target/target_template_source.go
=> Do not assume the operation is CREATE on audit

Makefile
=> Prepare v3.0.4-beta.2 release

config/manager/manager.yaml, deploy/gatekeeper.yaml
=> Bump deployment to v3.0.4-beta.2

pkg/audit/manager.go, test/bats/test.bats
Fixes #246 
Signed-off-by: Sertaç Özercan <sozercan@users.noreply.github.com>
=> Add total violations count per constraint

pkg/controller/constraint/constraint_controller.go
Signed-off-by: Emma McMillan <emma.mcmillan@microsoft.com>
=> Remove unnecessary err assignments

Makefile
=> Prepare v3.1.0-beta.0 release

Makefile
=> Prepare v3.1.0-beta.1 release

.travis.yml
=> Script must be a single line

docs/RELEASE.md
=> Tweak deploy instructions

README.md
=> Add finalizer FAQ

library/pod-security-policy/README.md, library/pod-security-policy/capabilities/constraint.yaml, library/pod-security-policy/capabilities/example.yaml, library/pod-security-policy/capabilities/src.rego, library/pod-security-policy/capabilities/src_test.rego, library/pod-security-policy/capabilities/template.yaml
=> Add capability PSP control aspect to library

.travis.yml
=> e2e tests were using the released image

.travis.yml
=> Remove `make patch-image` from travis build

chart/gatekeeper-operator/helm-modifications/helm-modifications.yaml, chart/gatekeeper-operator/templates/gatekeeper.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml
=> Add logtostderror flag to avoid need for filesystem access

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.1

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml
Reverting due to deadlock
This reverts commit 3f40e80a78063aa6203d2f7cf9a4330c5e3756cd.
=> Revert "Bump deployment v3.1.0-beta.1 (#359)"

pkg/watch/manager.go
The watch manager was creating a blocking channel in a place where an
error could mean that channel is never closed. This fixes the issue.
=> Fix deadlock.

Makefile
=> Prepare v3.1.0-beta.2 release

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.2

chart/gatekeeper-operator/generate_helm_template.sh, chart/gatekeeper-operator/templates/gatekeeper.yaml
I found that the replica count wasn't being respected in the deployment.
This fixes it for me :)
=> Fix the replicas value in the chart template

chart/gatekeeper-operator/templates/gatekeeper.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml
=> Advertise metrics port. This helps with Pod discovery in Prometheus.

pkg/controller/constraint/constraint_controller.go
current log message are misleading
=> not every reconcile adds a new constraint

chart/gatekeeper-operator/templates/gatekeeper.yaml, config/crd/bases/config.gatekeeper.sh_configs.yaml, deploy/gatekeeper.yaml, pkg/audit/stats_reporter.go, pkg/audit/stats_reporter_test.go, pkg/controller/constraint/constraint_controller.go, pkg/controller/constraint/constraint_controller_test.go, pkg/controller/constraint/stats_reporter.go, pkg/controller/constraint/stats_reporter_test.go, pkg/controller/constrainttemplate/constrainttemplate_controller.go, pkg/controller/constrainttemplate/stats_reporter.go, pkg/controller/constrainttemplate/stats_reporter_test.go, pkg/metrics/status.go, pkg/watch/stats_reporter.go, pkg/watch/stats_reporter_test.go, pkg/webhook/stats_reporter.go, pkg/webhook/stats_reporter_test.go
=> Add constraint template metrics

demo/agilebank/dryrun/k8suniqueingresshost_template.yaml, demo/agilebank/remediation/k8sbannedimagetags_template.yaml, demo/agilebank/templates/k8sallowedrepos_template.yaml, demo/agilebank/templates/k8scontainterlimits_template.yaml, demo/agilebank/templates/k8srequiredlabels_template.yaml, demo/agilebank/templates/k8suniqueserviceselector_template.yaml, demo/basic/bad/bad_template.yaml, demo/basic/templates/k8srequiredlabels_template.yaml, demo/basic/templates/k8srequiredlabels_template_external_data.yaml, demo/basic/templates/k8suniquelabel_template.yaml, example/templates/k8srequiredlabels_template.yaml, go.mod, go.sum, pkg/target/regolib/labelselector_test.rego, pkg/target/regolib/src.rego, pkg/target/target.go, pkg/target/target_integration_test.go, pkg/target/target_template_source.go, pkg/webhook/policy_test.go, test/bats/tests/templates/k8scontainterlimits_template.yaml, test/bats/tests/templates/k8srequiredlabels_template.yaml, test/bats/tests/templates/k8suniquelabel_template.yaml
Also add more robust testing of target Rego and sneak in a cleanup
of vistigial template names.
Fixes #311
=> Make sure label selectors are checked against both old and new objects

Makefile
=> Prepare v3.1.0-beta.3 release

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.3

docs/RELEASE.md
in case that `REGISTRY` is set externally
=> add registry var to deployment versioning doc

pkg/audit/manager.go, pkg/audit/stats_reporter.go
=> Fix total violations per enforcementAction

README.md, go.sum, pkg/webhook/policy.go, pkg/webhook/policy_test.go
=> Fix dryrun denied admission

Makefile
=> Prepare v3.1.0-beta.4 release

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/helm-modifications/helm-modifications.yaml, chart/gatekeeper-operator/templates/gatekeeper.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.4

README.md
I missed this part of the README in the audit source PR.
Signed-off-by: Craig Tabita <ctab@google.com>
=> Update README Replicating Data section for new audit functionality

Makefile
=> Prepare v3.1.0-beta.5 release

chart/gatekeeper-operator/helm-modifications/helm-modifications.yaml, chart/gatekeeper-operator/templates/gatekeeper.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.5

config/rbac/kustomization.yaml, config/rbac/role.yaml, config/rbac/webhook_permissions_patch.yaml, manifest_staging/chart/gatekeeper-operator/templates/gatekeeper.yaml, manifest_staging/deploy/gatekeeper.yaml, pkg/webhook/webhook.go
=> Only allow modification of the Gatekeeper webhook configuration

pkg/controller/constraint/constraint_controller.go
=> Log constraint addition after successful add to OPA, not after error

pkg/controller/config/config_controller.go, pkg/controller/config/config_controller_test.go
=> Remove config finalizer

go.mod, go.sum, manifest_staging/chart/gatekeeper-operator/templates/gatekeeper.yaml, manifest_staging/deploy/gatekeeper.yaml, pkg/util/ha_status.go, pkg/util/ha_status_test.go, vendor/github.com/open-policy-agent/frameworks/constraint/deploy/crds.yaml, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1alpha1/constrainttemplate_types.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1alpha1/zz_generated.conversion.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1beta1/zz_generated.conversion.go, vendor/github.com/open-policy-agent/frameworks/constraint/pkg/core/templates/constrainttemplate_types.go, vendor/modules.txt
=> Add ObservedGeneration field to ByPod status

library/pod-security-policy/users/template.yaml
=> Fix JSONSchema for RunAsUser PSP constraint template

Makefile, chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/values.yaml, manifest_staging/chart/gatekeeper-operator/Chart.yaml, manifest_staging/chart/gatekeeper-operator/values.yaml
=> Update release-manifest and chart

Makefile
=> Prepare v3.1.0-beta.6 release

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/templates/gatekeeper.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml, manifest_staging/chart/gatekeeper-operator/Chart.yaml, manifest_staging/chart/gatekeeper-operator/values.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.6

pkg/controller/constrainttemplate/constrainttemplate_controller.go
=> Set "created" status on update for constraint templates

pkg/audit/manager.go
=> Uniquify constraint kinds in audit

Makefile
=> Prepare v3.1.0-beta.7 release

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/templates/gatekeeper.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml, manifest_staging/chart/gatekeeper-operator/Chart.yaml, manifest_staging/chart/gatekeeper-operator/values.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.7

library/general/httpsonly/example.yaml
=> fix httpsonly ingress yaml example

pkg/audit/manager.go
=> remove deprecated flags

config/manager/manager.yaml, manifest_staging/deploy/gatekeeper.yaml
=> use default audit interval

README.md
=> Add fail-open info nearer top of README

chart/gatekeeper-operator/templates/gatekeeper.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml, manifest_staging/chart/gatekeeper-operator/templates/gatekeeper.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Drop Linux capabilities

chart/gatekeeper-operator/templates/gatekeeper.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml, manifest_staging/chart/gatekeeper-operator/templates/gatekeeper.yaml, manifest_staging/chart/gatekeeper-operator/values.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Add seccomp profile

pkg/controller/config/config_controller.go, pkg/controller/controller.go
=> Clear opa cache for CT

go.mod, pkg/webhook/policy.go
=> Fix self manage to compare username

test/bats/test.bats, test/bats/tests/bad/bad_deployment.yaml
=> Test bad deployment in e2e

Makefile
=> Prepare v3.1.0-beta.8 release

chart/gatekeeper-operator/Chart.yaml, chart/gatekeeper-operator/generate_helm_template.sh, chart/gatekeeper-operator/helm-modifications/helm-modifications.yaml, chart/gatekeeper-operator/templates/gatekeeper.yaml, chart/gatekeeper-operator/values.yaml, config/manager/manager.yaml, deploy/gatekeeper.yaml, manifest_staging/chart/gatekeeper-operator/Chart.yaml, manifest_staging/chart/gatekeeper-operator/values.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Bump deployment v3.1.0-beta.8

library/general/containerresourceratios/constraint.yaml, library/general/containerresourceratios/example.yaml, library/general/containerresourceratios/kustomization.yaml, library/general/containerresourceratios/src.rego, library/general/containerresourceratios/src_test.rego, library/general/containerresourceratios/template.yaml
Signed-off-by: yaron-idan <yaronidan@gmail.com>
=> add constraint resources from CLA user

pkg/watch/manager.go
=> Use RWMutex in watch manager to increase parallelism

README.md
=> Add example of using a deny-all template to view request obj

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
=> add issue and pr templates

pkg/webhook/policy.go
=> Fix expected service account name

docs/Metrics.md
Provides an updated list of metrics
=> add metrics doc

go.mod, go.sum, pkg/webhook/policy_benchmark_test.go, pkg/webhook/testdata/psp-all-violations/psp-constraints/host-filesystem-constraint.yaml, pkg/webhook/testdata/psp-all-violations/psp-constraints/host-namespaces-constraint.yaml, pkg/webhook/testdata/psp-all-violations/psp-constraints/host-network-constraint.yaml, pkg/webhook/testdata/psp-all-violations/psp-constraints/privileged-containers-constraint.yaml, pkg/webhook/testdata/psp-all-violations/psp-constraints/volumes-constraint.yaml, pkg/webhook/testdata/psp-all-violations/psp-pods/host-filesystem-example.yaml, pkg/webhook/testdata/psp-all-violations/psp-pods/host-namespaces-example.yaml, pkg/webhook/testdata/psp-all-violations/psp-pods/host-network-example.yaml, pkg/webhook/testdata/psp-all-violations/psp-pods/privileged-containers-example.yaml, pkg/webhook/testdata/psp-all-violations/psp-pods/volumes-example.yaml, pkg/webhook/testdata/psp-all-violations/psp-templates/host-filesystem-template.yaml, pkg/webhook/testdata/psp-all-violations/psp-templates/host-namespace-template.yaml, pkg/webhook/testdata/psp-all-violations/psp-templates/host-network-ports-template.yaml, pkg/webhook/testdata/psp-all-violations/psp-templates/privileged-containers-template.yaml, pkg/webhook/testdata/psp-all-violations/psp-templates/volume-template.yaml, test/clients/noop_client.go
- The PR performs a benchmark of Gatekeeper's validating handler. 
- A sample of PSP constraint templates are pre-loaded into OPA. Each subtest pre-loads M constraints where M varies from 5 to 100000. For each of the M constraints, number of admission requests that can be processed in 1 second is measured.
Fixes #
- These tests do not measure the HTTP roundtrip to/from kube-api-server
Current results:
cores: 8
mem: 16GB
> goos: darwin
> goarch: amd64
> pkg: github.com/open-policy-agent/gatekeeper/pkg/webhook
> BenchmarkValidationHandler/5-8 	     129 …
=> validation handler benchmark tests

cmd/build/helmify/static/README.md, cmd/build/helmify/static/values.yaml
=> update helmify values for nodeSelector

docs/RELEASE.md
`promote-staging-manifest` step got accidently removed, re-adding it
=> update release doc

README.md
Helm repo is available now, updating readme with instructions
=> Update helm instructions

config/rbac/role.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-manager-role-clusterrole.yaml, manifest_staging/deploy/gatekeeper.yaml, pkg/controller/config/config_controller.go
=> Update rbac to include psp

Makefile
Missed tagging dev tag before pushing
Fixes #
=> Fix dev tag push

library/pod-security-policy/users/src.rego, library/pod-security-policy/users/src_test.rego, library/pod-security-policy/users/template.yaml
=> Fix users psp for no securityContext

main.go
This PR adds the ability to set the format for log severity.
Fixes: #622 
=> Add ability to set log severity format

.github/workflows/workflow.yaml, Makefile, cmd/build/helmify/static/README.md, cmd/build/helmify/static/values.yaml, docs/RELEASE.md, manifest_staging/charts/gatekeeper/README.md, manifest_staging/charts/gatekeeper/values.yaml, manifest_staging/deploy/gatekeeper.yaml
#665
Fixes #665
- Currently images do not exist in Docker Hub
- There are a few references to Quay in README that needs to be updated when a new release is cut
- We will need to update secrets in Github to point to Docker Hub
=> Migrate to docker hub

cmd/build/helmify/static/values.yaml, config/manager/manager.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml, manifest_staging/charts/gatekeeper/values.yaml, manifest_staging/deploy/gatekeeper.yaml, test/bats/helpers.bash, test/bats/test.bats
Default multi-pod deployment for webhook
Fixes #
=> Default multi-pod deployment for webhook

pkg/webhook/policy.go
alternative for https://github.com/open-policy-agent/gatekeeper/pull/715
=> extract tracing logic into a method

Makefile, config/webhook/webhook_patch.yaml, go.mod, go.sum, manifest_staging/charts/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml, manifest_staging/deploy/gatekeeper.yaml
...and update controller-gen to `v0.3.0`
Fixes #697
=> Remove control-plane namespace selector

README.md
**What this PR does / why we need it**: 
Fixes #740 
=> Update Readme with namespace exclusion

pkg/audit/manager.go
https://github.com/open-policy-agent/gatekeeper/issues/778#issuecomment-673402092
Fixes #778
=> Fix audit List loop when list returns an error

Makefile, cmd/build/helmify/kustomize-for-helm.yaml, config/manager/manager.yaml, manifest_staging/charts/gatekeeper/templates/config-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/templates/constraintpodstatus-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/templates/constrainttemplate-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/templates/constrainttemplatepodstatus-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml, manifest_staging/deploy/gatekeeper.yaml
Update audit container name to `manager`
Fixes #762 
=> Update audit container name

.github/workflows/workflow.yaml
Release action is broken due to https://github.com/marvinpinto/actions/issues/39
Fixes #
=> fix release action

README.md
=> Update readme with audit-match-kind-only flag

docs/RELEASE.md
=> update release doc for release branches

docs/Release_Management.md
Fixes #
Pretty much same content as https://docs.google.com/document/d/1TR6S8GXkqC12EFk3TysetH2QzCBG_JTrPX05vMNy_bg/edit?usp=sharing
=> Add release management doc

.github/workflows/workflow.yaml
- Tag was not set correctly to avoid image override in `tagged-release` job
- Setting unit test as a requirement for `pre-release` and `tagged-release` jobs
- Run `pre-release` job on `release-*` branches
Fixes #
=> Fix publish tag and add unit test as a requirement

docs/design/README.md
=> Add Namespace Exclusion Design doc

pkg/webhook/certs.go
Signed-off-by: rbtr <rbtr@users.noreply.github.com>
Fixes #
=> Automated cherry pick of #811 upstream release 3.1

Makefile
Signed-off-by: rbtr <rbtr@users.noreply.github.com>
Fixes #
=> Automated cherry pick of #816 upstream release 3.1 1600369502

README.md
Fixes https://github.com/open-policy-agent/gatekeeper/issues/854
=> Update readme for helm force-update

test/bats/helpers.bash, test/bats/test.bats
Signed-off-by: luckoseabraham <luckose4u@gmail.com>
**What this PR does / why we need it**: Removes sleep introduced in https://github.com/open-policy-agent/gatekeeper/pull/860, but fixed in https://github.com/open-policy-agent/gatekeeper/pull/861
Fixes #
=> Removing the sleep as its no longer needed. Tests have been fixed.

pkg/audit/manager.go
=> Continue audit with orphaned apiservices

test/bats/test.bats, test/bats/tests/bad/ignore_label_ns.yaml
=> Automated cherry pick of #861 #863 #873 upstream release 3.1 1603913978

Dockerfile
=> Automated cherry pick of #878 upstream release 3.1 1603914308

config/webhook/webhook_patch.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Automated cherry pick of #871 upstream release 3.1 1603912279

.github/workflows/workflow.yaml
=> Automated cherry pick of #876 upstream release 3.1 1603914574

pkg/audit/manager.go
=> Automated cherry pick of #944 upstream release 3.1 1605043564

pkg/audit/manager.go
=> Automated cherry pick of #944 upstream release 3.2 1605043500

docs/design/README.md
Add the new, recently-proposed mutation design docs
Fixes #
=> Add new mutation design docs

test/bats/helpers.bash, test/bats/test.bats, test/bats/tests/bad/bad_cm.yaml, test/bats/tests/bad/bad_cm_audit.yaml, test/bats/tests/bad/bad_deployment.yaml, test/bats/tests/bad/ignore_label_ns.yaml, test/bats/tests/bad/no_dupe_cm_2.yaml, test/bats/tests/bad/opa_no_limits.yaml, test/bats/tests/constraints/all_cm_gatekeeper_label_unique.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper-dryrun.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper_audit.yaml, test/bats/tests/constraints/containers_must_be_limited.yaml, test/bats/tests/good/good_cm.yaml, test/bats/tests/good/good_ns.yaml, test/bats/tests/good/no_dupe_cm.yaml, test/bats/tests/good/opa.yaml, test/bats/tests/good/playground_ns.yaml, test/bats/tests/sync_with_exclusion.yaml
Should fix flaky e2e tests
Fixes #942 
=> Fix e2e test flakiness

config/rbac/role.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-manager-role-clusterrole.yaml, manifest_staging/deploy/gatekeeper.yaml, pkg/controller/add_assignmetadata.go, pkg/controller/assignmetadata/assignmetadata_controller.go
Add a AssignMetadata controller.
Requires #938 to be merged
Fixes #906
=> Add AssignMetadata controller

.github/workflows/workflow.yaml
=> Cherry pick #969 "fix set-env deprecation" to release-3.2

pkg/mutation/assign_mutator.go, pkg/mutation/assignmeta_mutator.go, pkg/mutation/mutator.go, pkg/mutation/system_test.go
Add Value() function to mutators.
The function will return the value to be set by the mutator.
=> Add Value function to mutators

test/bats/helpers.bash, test/bats/test.bats, test/bats/tests/bad/bad_cm.yaml, test/bats/tests/bad/bad_cm_audit.yaml, test/bats/tests/bad/bad_deployment.yaml, test/bats/tests/bad/ignore_label_ns.yaml, test/bats/tests/bad/no_dupe_cm_2.yaml, test/bats/tests/bad/opa_no_limits.yaml, test/bats/tests/constraints/all_cm_gatekeeper_label_unique.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper-dryrun.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper_audit.yaml, test/bats/tests/constraints/containers_must_be_limited.yaml, test/bats/tests/good/good_cm.yaml, test/bats/tests/good/good_ns.yaml, test/bats/tests/good/no_dupe_cm.yaml, test/bats/tests/good/opa.yaml, test/bats/tests/good/playground_ns.yaml, test/bats/tests/sync_with_exclusion.yaml
=> Automated cherry pick of #964 upstream release 3.1

docs/RELEASE.md
=> add documentation for cherry pick

.github/workflows/workflow.yaml
=> Automated cherry pick of #969 upstream release 3.1

Makefile, config/overlays/mutation_webhook/kustomization.yaml, config/overlays/mutation_webhook/mutations.gatekeeper.sh_assign.yaml, config/overlays/mutation_webhook/mutations.gatekeeper.sh_assignmetadata.yaml, config/overlays/mutation_webhook/webhook.yaml, config/overlays/mutation_webhook/webhook_permissions_patch.yaml, main.go, pkg/webhook/common.go, pkg/webhook/mutation.go, pkg/webhook/stats_reporter.go, pkg/webhook/stats_reporter_test.go
The gatekeeper mutation feature requires a new mutating webhook to be added.
This PR adds the the mutating webhook.
=> Add mutating webhook

main.go, pkg/controller/assignmetadata/assignmetadata_controller.go, pkg/controller/config/config_controller.go, pkg/controller/constraint/constraint_controller.go, pkg/controller/constrainttemplate/constrainttemplate_controller.go, pkg/controller/controller.go, pkg/webhook/mutation.go, pkg/webhook/namespacelabel.go, pkg/webhook/policy.go, pkg/webhook/webhook.go
Create a mutation cache and add it to controller and webhook.
This PR depends on multiple unmerged PR's 
These must be merged before this: #916, #926, #928, #938, ...
=> Add mutation cache to controller and webhook

pkg/mutation/conversion_test.go
Signed-off-by: mmirecki <mmirecki@redhat.com>
Update TestAssignMetadataToMutator to check mutator and path
=> Update TestAssignMetadataToMutator to check mutator and path

pkg/controller/add_assign.go, pkg/controller/assign/assign_controller.go
Add controller for assign mutation
Fixes #905 
=> Add assign controller

Makefile
Cherry picks #925 to release-3.2
=> Automated cherry pick of #925 upstream release 3.2

Makefile
Cherry picks #925 to release-3.1
=> Automated cherry pick of #925 upstream release 3.1

pkg/webhook/common.go, pkg/webhook/mutation.go, pkg/webhook/namespacelabel.go, pkg/webhook/policy.go
Connect the mutation webhook with the mutation system.
=> Connect mutation webhook with mutation system

pkg/controller/add_assignmetadata.go, pkg/controller/assignmetadata/assignmetadata_controller.go
Follow up to https://github.com/open-policy-agent/gatekeeper/pull/1019#discussion_r541452819
Fixes #
=> Update assignmetadata controller pkg

pkg/mutation/system.go
=> Update comment on `Mutate` function

pkg/mutation/system.go
=> Fix assign mutation panic

.github/workflows/workflow.yaml, Makefile
=> Automated cherry pick of #1039 upstream release 3.2 1611182140

pkg/audit/manager.go, pkg/upgrade/manager.go, pkg/util/selfLink.go, pkg/util/selfLink_test.go
Cherry picking #1007 (selfLink fix for k8s v1.20) for release-3.2 
Fixes #
**Special notes for your reviewer**:Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
=> Automated cherry pick of #1007 upstream release 3.2 1611174887

website/docusaurus.config.js
Fixes #1130 
anyone can request `apiKey` at https://docsearch.algolia.com/ it crawls every 24 hours
example `apiKey` in the upstream repo: https://github.com/facebook/docusaurus/blob/master/website/docusaurus.config.js#L303
=> add search to docs website

apis/addtoscheme_assignmetadata_v1alpha1.go, go.mod, main.go, pkg/controller/assignmetadata/assignmetadata_controller.go, pkg/controller/config/config_controller_test.go, pkg/controller/constrainttemplate/constrainttemplate_controller_test.go, pkg/controller/constrainttemplatestatus/constrainttemplatestatus_controller_test.go, pkg/mutation/system.go, pkg/readiness/ready_tracker.go, pkg/readiness/ready_tracker_test.go, pkg/readiness/setup.go, pkg/readiness/testdata/99-assignmetadata.yaml, pkg/readiness/testdata_test.go, pkg/target/target.go, pkg/webhook/mutation_test.go
=> Mutation cache warming

website/sidebars.js
Adding mutation doc to sidebar.
The mutation doc will be in the last position for now.
=> Add mutation docs to sidebar

pkg/webhook/namespacelabel.go, pkg/webhook/namespacelabel_test.go
=> Allow namespaces by prefix

Makefile, deploy/experimental/gatekeeper-mutation.yaml
Signed-off-by: mmirecki <mmirecki@redhat.com>
=> Add gatekeeper mutation yaml

website/docs/audit.md, website/docs/customize-admission.md, website/docs/exempt-namespaces.md
Signed-off-by: Takao Shibata <chise.alter.pasta@gmail.com>
Some anchor in follow website doesn't work. This PR fix them.
- https://open-policy-agent.github.io/gatekeeper/website/docs/audit
- https://open-policy-agent.github.io/gatekeeper/website/docs/exempt-namespaces
- https://open-policy-agent.github.io/gatekeeper/website/docs/customize-admission
None
None
=> website: fix anchor

website/docs/mutation.md
Signed-off-by: Takao Shibata <chise.alter.pasta@gmail.com>
This PR fix whitespace in manifest in https://open-policy-agent.github.io/gatekeeper/website/docs/mutation .
None
None
=> website: fix whitespace in manifest

cmd/build/helmify/kustomize-for-helm.yaml, manifest_staging/charts/gatekeeper/crds/assign-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/crds/assignmetadata-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/crds/config-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/crds/constraintpodstatus-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/crds/constrainttemplate-customresourcedefinition.yaml, manifest_staging/charts/gatekeeper/crds/constrainttemplatepodstatus-customresourcedefinition.yaml
With the removal of helm 2 support, crd-install helm hook should be removed as well.
Fixes #
=> fix(helm) - Remove crd-install helm hook

website/docusaurus.config.js
Fixes `edit this page` link in the docs website
Fixes #
=> fix edit page link

deploy/experimental/gatekeeper-mutation.yaml
=> Update experimental manifest with v3.4.0 image

website/docs/metrics.md, website/docs/violations.md
=> document warn enforcement action

website/docs/mutation.md
Fixes #
https://github.com/open-policy-agent/gatekeeper/issues/1257
=> fixing docs for Mutation documentation page securitycontext example

docs/design/README.md
=> Add v1beta1 CRD deprecation doc

website/docs/mutation.md
Fix the errors of Assign example yamls in mutation doc.
=> Fix mutation docs errors

website/docs/install.md
The install instructions should point to the latest release (3.4)
=> Update linked release version to 3.4

test/bats/test.bats
=> fix curl image used for e2e

test/bats/test.bats
Cherry picking curl image change into release-3.4 branch
Fixes #
=> fix curl image in release 3.4 branch

.github/workflows/upgrade.yaml
After #1338 is merged, we'll be able to pull that release branch to avoid missing image
Fixes #
=> fix upgrade test

.github/workflows/upgrade.yaml, Makefile
=> add namespace to upgrade test

pkg/controller/assign/assign_controller.go, pkg/controller/assignmetadata/assignmetadata_controller.go, pkg/mutation/mutators/assign_mutator.go, pkg/mutation/mutators/assignmeta_mutator.go, pkg/mutation/mutators/conversion_test.go, pkg/mutation/mutators/testhelpers/dummy_mutator.go, pkg/mutation/path/parser/node.go, pkg/mutation/path/parser/parser.go, pkg/mutation/path/parser/parser_test.go, pkg/mutation/path/tester/tester.go, pkg/mutation/path/tester/tester_test.go, pkg/mutation/path/token/scanner.go, pkg/mutation/path/token/scanner_test.go, pkg/mutation/schema/schema_test.go, pkg/mutation/system_test.go, pkg/mutation/types/mutator.go, pkg/mutation/types/mutator_test.go, pkg/readiness/ready_tracker_test.go
Fixes #
**Special notes for your reviewer**:Forbid creating mutations which require sepecific paths but forbid
their parents.
Signed-off-by: Will Beason <willbeason@google.com>Forbid creating mutations which require sepecific paths but forbid
their parents.
=> Cherry pick of #1317 and #1362: validate parent and children Conditions

.github/workflows/workflow.yaml, Makefile, cmd/build/helmify/kustomize-for-helm.yaml, config/overlays/mutation_webhook/kustomization.yaml, config/overlays/mutation_webhook/status.gatekeeper.sh_mutatorpodstatuses.yaml, manifest_staging/charts/gatekeeper/crds/mutatorpodstatus-customresourcedefinition.yaml
=> Cherry pick of #1389 origin release 3.5 1624406341

.github/workflows/website.yaml, .github/workflows/workflow.yaml, website/package-lock.json, website/package.json
Upgrade git workflow dependencies.
Upgrade docasaurus dependencies.
Run "yarn start" to update package lockfiles.
This will stop dependabot from constantly opening PRs against every fork of this repository.
=> Make dependabot-recommended changes

pkg/mutation/mutators/assign_mutator.go, pkg/mutation/mutators/assignmeta_mutator.go
Instead of keeping the assigned value for AssignMutator/AssignMetadataMutator as json, cache the unmarshalled value.
Unmarshalling JSON is incredibly expensive, even for simple values. We should avoid this when possible. Instead, we should cache the value to assign, and then deepcopy it when needed. Fortunately, the runtime package provides us a method just for this!
For AssignMetadata we just cache the string value since it is only valid to assign strings with an AssignMetadataMutator.
This change results in a ~90% reduction in compute time for most common uses. The existing benchmarks are for assigning a string, but the speedup is even more for complex assigned values.
Change in AssingMutator benchmarks:
```
$ benchstat before.txt after.txt 
name …
```
=> [mutators] deepcopy cached value instead of unmarshalling json

website/docusaurus.config.js
Reverts open-policy-agent/gatekeeper#1503
=> Revert "changes in the base url to fix the broken link"

website/docs/exempt-namespaces.md
Add mutation exclusion to docs
Fixes #
=> add mutation exclusion to doc

website/docs/externaldata.md, website/docs/mutation.md, website/versioned_docs/version-v3.7.x/externaldata.md, website/versioned_docs/version-v3.7.x/mutation.md
=> update docs for mutation beta

website/docs/install.md, website/versioned_docs/version-v3.6.x/install.md, website/versioned_docs/version-v3.7.x/install.md
This should be automated with CI but doing this manually for now. 
opened https://github.com/open-policy-agent/gatekeeper/issues/1688
Fixes #
=> update gatekeeper.yaml branch in install doc

pkg/webhook/mutation_test.go
=> Remove duplicate import

.github/workflows/workflow.yaml
https://github.com/open-policy-agent/gatekeeper/pull/1707
Fixes #
=> fail CI if go.mod changes are detected

website/docs/gator.md, website/sidebars.js, website/versioned_sidebars/version-v3.7.x-sidebars.json
=> Gator docs

website/versioned_docs/version-v3.7.x/gator.md
TIL: Docs have to be copied into the versioned folder.
=> Add copy of gator.md file to version-v3.7.x/

config/rbac/podsecuritypolicy.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-admin-podsecuritypolicy.yaml, manifest_staging/deploy/gatekeeper.yaml
=> Update psp to allow emptyDir

.github/dependabot.yml
=> chore: update dependabot prefix with semantic commits

website/docs/intro.md, website/versioned_docs/version-v3.6.x/intro.md, website/versioned_docs/version-v3.7.x/intro.md
Update website to indicate CNCF graduated status.
Signed-off-by: thomasmckay@redhat.com
=> fix: update CNCF to graduated in website

website/docs/exempt-namespaces.md, website/versioned_docs/version-v3.6.x/exempt-namespaces.md, website/versioned_docs/version-v3.7.x/exempt-namespaces.md
We had a user asking about difference
Slightly edited from @maxsmythe's comment here: https://github.com/open-policy-agent/gatekeeper/issues/1592#issuecomment-932618959
Fixes #
=> docs: namespace exclusion differences

website/docs/howto.md, website/versioned_docs/version-v3.6.x/howto.md, website/versioned_docs/version-v3.7.x/howto.md
Fixes #1797 
NOTE: Will update v3.7 and v3.6 version docs once the content in docs is approved.
=> docs: Add additional Constraint fields to howto

cmd/build/helmify/main.go, cmd/build/helmify/replacements.go, cmd/build/helmify/static/templates/upgrade-crds-hook.yaml, cmd/build/helmify/static/values.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-webhook-service-service.yaml, manifest_staging/charts/gatekeeper/templates/upgrade-crds-hook.yaml, manifest_staging/charts/gatekeeper/values.yaml
Fix a couple of spacing related formatting
=> chore: Remove unneeded spaces in helm chart

test/gator/test/fixtures/manifests/referential-data/disallowed_ingress.yaml, test/gator/test/fixtures/manifests/referential-data/inventory.yaml, test/gator/test/fixtures/policies/default/constraint_k8suniqueingresshost.yaml, test/gator/test/fixtures/policies/default/template_k8suniqueingresshost.yaml, test/gator/test/test.bats
=> test: Integration test for referential data in `gator test`

website/versioned_docs/version-v3.6.x/help.md
=> docs: remove developer doc from 3.6

website/docs/customize-startup.md, website/versioned_docs/version-v3.7.x/customize-startup.md
=> docs: customize-startup: fix typo

.github/workflows/workflow.yaml, config/manager/manager.yaml, manifest_staging/deploy/gatekeeper.yaml
Cherry-picking the following PRs to release-3.7.
- #1966
- #1986
Fixes #
=> fix: Update deployment to include mutation-status operation

website/docs/developers.md, website/docs/externaldata.md, website/docs/mutation.md, website/versioned_docs/version-v3.7.x/developers.md, website/versioned_docs/version-v3.7.x/externaldata.md
Adding documentation for external data mutation feature.
Ref: #1576 
=> docs: external data mutation

website/docs/developers.md, website/docs/externaldata.md, website/versioned_docs/version-v3.7.x/developers.md
Address PR comments from #2000.
Fixes #
=> docs: address comments from #2000

docs/design/README.md
=> docs: add compiler sharding

.github/workflows/workflow.yaml, Makefile
=> ci: bump kind and k8s versions

go.mod, go.sum, main.go, vendor/go.uber.org/automaxprocs/.codecov.yml, vendor/go.uber.org/automaxprocs/.gitignore, vendor/go.uber.org/automaxprocs/CHANGELOG.md, vendor/go.uber.org/automaxprocs/CODE_OF_CONDUCT.md, vendor/go.uber.org/automaxprocs/CONTRIBUTING.md, vendor/go.uber.org/automaxprocs/LICENSE, vendor/go.uber.org/automaxprocs/Makefile, vendor/go.uber.org/automaxprocs/README.md, vendor/go.uber.org/automaxprocs/automaxprocs.go, vendor/go.uber.org/automaxprocs/glide.yaml, vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go, vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go, vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups2.go, vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go, vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go, vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go, vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go, vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go, vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go, vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go, vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go, vendor/go.uber.org/automaxprocs/maxprocs/version.go, vendor/modules.txt
This helps address #1907 
Fixes #
=> perf: Integrate go.uber.org/automaxprocs

Makefile
=> add buildx-builder to gator docker build

docs/Release_Management.md
=> docs: clarify k8s support

website/docs/audit.md
Updating staging docs only as this change is only going in v3.9
Fixes #2133 
=> docs: add group and version to audit status violations

.github/workflows/codeql.yaml
forgot to remove pr checks from codeql. it takes too long to run for PRs
Fixes #
=> fix: remove prs from codeql

website/docs/externaldata.md
Follow-up PR for https://github.com/open-policy-agent/gatekeeper/pull/2121.
ref: #1576 
Fixes #
=> docs: TLS and mTLS documentation

Makefile
Fixes a bug in the release process where it accidentally bumped the tag of the curl image.
Fixes #
=> fix: sed on specific tag in `make release-manifest`

website/docs/audit.md, website/versioned_docs/version-v3.6.x/audit.md, website/versioned_docs/version-v3.7.x/audit.md, website/versioned_docs/version-v3.8.x/audit.md
Add singleton to audit doc since we have been getting more questions around this on slack lately.
Fixes #
=> docs: add singleton for audit

.github/stale.yml
Fixes #
All default config, except # of days to close changed from 7 to 14
=> ci: add stale bot config

website/docs/externaldata.md, website/versioned_docs/version-v3.7.x/externaldata.md, website/versioned_docs/version-v3.8.x/externaldata.md, website/versioned_docs/version-v3.9.x/externaldata.md
Link to template provider instead of dummy provider which was used for e2e
Fixes #
=> docs: link to template provider

website/docs/audit.md, website/docs/howto.md, website/versioned_docs/version-v3.6.x/audit.md, website/versioned_docs/version-v3.6.x/howto.md, website/versioned_docs/version-v3.7.x/audit.md, website/versioned_docs/version-v3.7.x/howto.md, website/versioned_docs/version-v3.8.x/audit.md, website/versioned_docs/version-v3.8.x/howto.md, website/versioned_docs/version-v3.9.x/audit.md, website/versioned_docs/version-v3.9.x/howto.md
Fixes #1138 
Will update version docs after approval.
=> docs: add fields that are not populated in audit

website/docusaurus.config.js
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
Updates reference to the Gatekeeper library website.
Fixes #
=> chore: updates gatekeeper website reference

.github/workflows/workflow.yaml, Makefile
=> ci: bump e2e k8s version

README.md, website/docs/library.md, website/versioned_docs/version-v3.6.x/library.md, website/versioned_docs/version-v3.7.x/library.md, website/versioned_docs/version-v3.8.x/library.md, website/versioned_docs/version-v3.9.x/library.md
Raises the visibility of the library website.
Fixes #
=> docs: Update library links to point to website

go.mod, go.sum, vendor/golang.org/x/net/AUTHORS, vendor/golang.org/x/net/CONTRIBUTORS, vendor/golang.org/x/net/html/render.go, vendor/golang.org/x/net/html/token.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/hpack/encode.go, vendor/golang.org/x/net/http2/hpack/hpack.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/sys/AUTHORS, vendor/golang.org/x/sys/CONTRIBUTORS, vendor/golang.org/x/sys/unix/mkerrors.sh, vendor/golang.org/x/sys/unix/syscall_aix.go, vendor/golang.org/x/sys/unix/zerrors_linux.go, vendor/modules.txt
=> fix: fix CVE-2022-27664

charts/artifacthub-repo.yml
Signed-off-by: Nilekh Chaudhari <1626598+nilekhc@users.noreply.github.com>
Adds Verified Publisher claim metadata for Artifact hub. 
Fixes #
=> feat: adds artifact hub metadata

website/docs/audit.md, website/versioned_docs/version-v3.6.x/audit.md, website/versioned_docs/version-v3.7.x/audit.md, website/versioned_docs/version-v3.8.x/audit.md, website/versioned_docs/version-v3.9.x/audit.md
=> docs: update audit userinfo

website/docs/mutation.md
=> docs: Change mutation to Stable

website/README.md
Search index was not working for v3.10 for some reason, adding steps to fix
Fixes #
=> docs: search docs

pkg/audit/manager.go
=> fix: Automated cherry pick of #2335: inject ns into review when auditing from cache

demo/agilebank/README.md, demo/agilebank/bad_resources/deployment_nolimit.yaml, demo/agilebank/demo.sh, demo/agilebank/expansion_templates/expand_deployment_expansiontemplate.yaml, demo/agilebank/good_resources/opa.yaml, demo/agilebank/warn/bad_resource/duplicate_ing.yaml, demo/agilebank/warn/unique-ingress-host.yaml
=> docs: add expansion and warn to demo

website/docs/library.md, website/docusaurus.config.js, website/versioned_docs/version-v3.10.x/library.md, website/versioned_docs/version-v3.6.x/library.md, website/versioned_docs/version-v3.7.x/library.md, website/versioned_docs/version-v3.8.x/library.md, website/versioned_docs/version-v3.9.x/library.md
=> docs: rename policy library on website

cmd/build/helmify/static/Chart.yaml, manifest_staging/charts/gatekeeper/Chart.yaml
Removes some noise in helm lint
```
==> Linting .
[INFO] Chart.yaml: icon is recommended
```
=> chore(helmify): Add icon to Chart.yaml

.github/workflows/workflow.yaml, Makefile
=> ci: add k8s 1.26

pkg/gator/verify/read_suites.go, pkg/gator/verify/read_suites_test.go
cherry pick for https://github.com/open-policy-agent/gatekeeper/pull/2498
=> fix: cutpath for ../ paths

website/docs/expansion.md, website/versioned_docs/version-v3.10.x/expansion.md, website/versioned_docs/version-v3.11.x/expansion.md
DaemonSet -> DaemonSet
Signed-off-by: triangularcover <labytnangi1980@gmail.com>
=> docs: Fix typo in website docs

website/docs/expansion.md, website/versioned_docs/version-v3.10.x/expansion.md, website/versioned_docs/version-v3.11.x/expansion.md
ReplicationController and Jobs kubernetes resource kinds belong to different api groups
Fixes #
=> docs: fix example code snippet for docs

website/docs/developers.md, website/versioned_docs/version-v3.10.x/developers.md, website/versioned_docs/version-v3.11.x/developers.md, website/versioned_docs/version-v3.7.x/developers.md, website/versioned_docs/version-v3.8.x/developers.md, website/versioned_docs/version-v3.9.x/developers.md
Fixes https://github.com/kubernetes/k8s.io/issues/4780
=> docs: update k8s.gcr.io to registry.k8s.io

website/versioned_docs/version-v3.11.x/mutation-background.md, website/versioned_sidebars/version-v3.11.x-sidebars.json
Old PR got merged post 3.11 release
Fixes #
=> docs: Add mutation background to 3.11

website/src/pages/index.js
The button that links to the policy library on the homepage is not currently correct, this fixes that
=> docs: fix link to policy library on website

index.html
This should complete the process of fixing the redirect
=> docs: fix landing page redirect

.github/workflows/release.yaml
due to https://github.com/step-security/secure-repo/issues/2109
Fixes #
=> ci: fix release action

website/docs/expansion.md
=> docs: Fix typo in ExpansionTemplate

docs/design/README.md
**What this PR does / why we need it**: Keeping the status of proposed/implemented designs consistent.
Fixes #
=> chore: removing pubsub design from proposed section

.github/dependabot.yml
=> ci: group dependabot prs

.github/workflows/website.yaml
Validate docs without deploying
Fixes #
=> ci: validate docs

website/docs/customize-startup.md, website/docs/mutation.md, website/versioned_docs/version-v3.10.x/customize-startup.md, website/versioned_docs/version-v3.10.x/mutation.md, website/versioned_docs/version-v3.11.x/customize-startup.md, website/versioned_docs/version-v3.11.x/mutation.md, website/versioned_docs/version-v3.12.x/customize-startup.md, website/versioned_docs/version-v3.12.x/mutation.md, website/versioned_docs/version-v3.13.x/customize-startup.md, website/versioned_docs/version-v3.13.x/mutation.md, website/versioned_docs/version-v3.7.x/customize-startup.md, website/versioned_docs/version-v3.7.x/mutation.md, website/versioned_docs/version-v3.8.x/customize-startup.md, website/versioned_docs/version-v3.8.x/mutation.md, website/versioned_docs/version-v3.9.x/customize-startup.md, website/versioned_docs/version-v3.9.x/mutation.md
Completely screwed up Git history on https://github.com/open-policy-agent/gatekeeper/pull/2926 - opening this in favor
=> docs: add docs on mutation annotations

.github/workflows/workflow.yaml
"fixes" https://github.com/open-policy-agent/gatekeeper/issues/3004
=> ci: lint timeout m 5->7

.github/workflows/release.yaml
Co-authored-by: sozercan <sozercan@users.noreply.github.com>
Co-authored-by: Sertac Ozercan <sozercan@gmail.com>**What this PR does / why we need it**:
Cherry pick #3042 to release-3.13
=> chore: chery pick #3042

.github/workflows/release.yaml
=> ci: filter out helm gh pages image from release cleanup

.github/workflows/release.yaml
Co-authored-by: sozercan <sozercan@users.noreply.github.com>
Co-authored-by: Sertac Ozercan <sozercan@gmail.com>**What this PR does / why we need it**:
Cherry pick #3053 to release 3.13
=> ci: cherry pick #3053

.github/workflows/pre-release.yaml, .github/workflows/release.yaml
Co-authored-by: JaydipGabani <JaydipGabani@users.noreply.github.com>**What this PR does / why we need it**:
Cherry picking for release 3.14
Drops arm/v7 images for crd image. see #3074 
Fixes #
=> ci: cherry-pick #3074 for release-3.14

Makefile
Co-authored-by: sozercan <sozercan@users.noreply.github.com>
Co-authored-by: Sertac Ozercan <sozercan@gmail.com>**What this PR does / why we need it**:
Fixes #
=> chore: bump kubectl for release 3.13

docs/Release_Management.md
Clarify RC release soak timeframe
Fixes #
=> docs: clarify rc release

pkg/audit/manager.go
=> fix: fixing panic in error log

pkg/audit/manager.go
(cherry picked from commit 88033b15e2a57ad33567d8d0032a9191062193da)
Fixes #
=> fix: fixing panic in debug log (#3244) cherry-pick 

website/docs/install.md, website/versioned_docs/version-v3.15.x/install.md
=> docs: pointing install command to correct version

website/docs/expansion.md
Fixes #3290 
I will add to versioned docs after lgtm
=> docs: document constraint match.source

cmd/build/helmify/main.go, manifest_staging/charts/gatekeeper/templates/gatekeeper-audit-deployment.yaml, manifest_staging/charts/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
Signed-off-by: James Bruce <james.bruce@ba.com>
Co-authored-by: Rita Zhang <rita.z.zhang@gmail.com>
(cherry picked from commit 902a1b4f7fd97d6ee59a7078fa28485f4e1a018f)
Details in https://github.com/open-policy-agent/gatekeeper/pull/3240
=> feat: Update audit and controller manager with pod labels (#3240) (cherry pick)

website/docs/externaldata.md, website/versioned_docs/version-v3.15.x/externaldata.md
Adds docs for Kubernetes API external data providers.
Fixes #2716 
=> docs: updates docs with new external data provider

website/docs/mutation.md, website/versioned_docs/version-v3.10.x/mutation.md, website/versioned_docs/version-v3.11.x/mutation.md, website/versioned_docs/version-v3.12.x/mutation.md, website/versioned_docs/version-v3.13.x/mutation.md, website/versioned_docs/version-v3.14.x/mutation.md, website/versioned_docs/version-v3.15.x/mutation.md, website/versioned_docs/version-v3.16.x/mutation.md, website/versioned_docs/version-v3.7.x/mutation.md, website/versioned_docs/version-v3.8.x/mutation.md, website/versioned_docs/version-v3.9.x/mutation.md
Quote the subPath conditional. Otherwise, copy + paste the YAML is invalid.
Fixes #
=> docs: quote the subPath conditional

website/versioned_docs/version-v3.16.x/install.md
=> chore: Patch docs for 3.16.3 release

Makefile
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>**What this PR does / why we need it**:
follow up on #3427 
Fixes #
=> ci: revert kubebuilder custom env

.github/workflows/workflow.yaml
=> fix: fixing artifact upload error

pkg/controller/constrainttemplate/constrainttemplate_controller.go
Signed-off-by: martijnvdp <m.vanderploeg@nl.ccv.eu>
Co-authored-by: Jaydipkumar Arvindbhai Gabani <gabanijaydip@gmail.com>
(cherry picked from commit 7429d70bb2b7f688df71dd0f35d49682f3597fe0)
Fixes #
=> fix: vap error logging for rego only templates, cherry-pick (#3520)

website/docs/mutation.md
changing hierarchy of the imagePullPolicy example in order to have a ToC entry (and link) on the website
update documentation, have a ToC entry (and link) on the website for the specific example
Fixes #
=> docs: update mutation docs

.github/workflows/scan-vulns.yaml
**What this PR does / why we need it**: Solve CI errors `2024-11-11T10:44:36.531Z	FATAL	init error: DB error: failed to download vulnerability DB: database download error: OCI repository error: 1 error occurred:
* GET https://ghcr.io/v2/aquasecurity/trivy-db/manifests/2: TOOMANYREQUESTS: retry-after: 512.599µs, allowed: 44000/minute` - https://github.com/open-policy-agent/gatekeeper/actions/runs/11776971327/job/32800423747?pr=3690
Fixes #
=> ci: updating trivy version

website/docs/validating-admission-policy.md, website/versioned_docs/version-v3.17.x/validating-admission-policy.md
Fixes #3693
https://github.com/open-policy-agent/gatekeeper/issues/3693
=> docs: Fix vapb argument

.github/workflows/scan-vulns.yaml
trivy db is getting throttled due to unknown ghcr throttling, adding official fallback mirrors from aws and dockerhub
Fixes #
=> ci: fix trivy throttling

.github/workflows/scan-vulns.yaml
=> chore: updating deprecated flag for trivy

pkg/controller/constraint/constraint_controller.go, pkg/controller/constraint/constraint_controller_test.go
(cherry picked from commit 14e6c8ad64de835b2daaa00ae1185c822cdf7647)
Fixes #
=> fix: fixing nil pointer error when converting VAPB from v1beta1 to v1, CP (#3754)

go.mod, go.sum, vendor/golang.org/x/net/html/doc.go, vendor/golang.org/x/net/html/doctype.go, vendor/golang.org/x/net/html/foreign.go, vendor/golang.org/x/net/html/iter.go, vendor/golang.org/x/net/html/node.go, vendor/golang.org/x/net/html/parse.go, vendor/golang.org/x/net/http2/client_conn_pool.go, vendor/golang.org/x/net/http2/config.go, vendor/golang.org/x/net/http2/config_go124.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/http2/unencrypted.go, vendor/golang.org/x/sys/unix/syscall_dragonfly.go, vendor/golang.org/x/sys/windows/dll_windows.go, vendor/modules.txt
**What this PR does / why we need it**: Fixes [CVE-2024-45337](https://nvd.nist.gov/vuln/detail/CVE-2024-45337), and [CVE-2024-45338](https://nvd.nist.gov/vuln/detail/CVE-2024-45338)
Fixes #
=> chore: bumping net, crypto dep

go.mod, go.sum, vendor/golang.org/x/net/html/doc.go, vendor/golang.org/x/net/html/doctype.go, vendor/golang.org/x/net/html/foreign.go, vendor/golang.org/x/net/html/iter.go, vendor/golang.org/x/net/html/node.go, vendor/golang.org/x/net/html/parse.go, vendor/golang.org/x/net/http2/client_conn_pool.go, vendor/golang.org/x/net/http2/config.go, vendor/golang.org/x/net/http2/config_go124.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/http2/unencrypted.go, vendor/golang.org/x/sys/unix/syscall_dragonfly.go, vendor/golang.org/x/sys/windows/dll_windows.go, vendor/modules.txt
(cherry picked from commit a8eb788be6a4d9144e3836dc626eb0d700e02723)
Fixes #
=> chore: bumping net, crypto dep, CP (#3766)

website/docs/opa-versions.md, website/versioned_docs/version-v3.17.x/install.md, website/versioned_docs/version-v3.17.x/opa-versions.md
**What this PR does / why we need it**: This - https://github.com/open-policy-agent/gatekeeper/actions/runs/12942416954/job/36102625615 - workflow failed due to not having the latest fixes for patching docs in 3.17 branch. 
Fixes #
=> chore: Patch docs for 3.17.2 release

pkg/drivers/k8scel/transform/cel_snippets.go
**What this PR does / why we need it**: I couldn't find any reference to `BindObjectCEL` function.
Fixes #
=> chore: removing unused function

website/docs/gator.md
**What this PR does / why we need it**: Addressing nits from comment - https://github.com/open-policy-agent/gatekeeper/pull/3809#discussion_r2001646047
Fixes #
=> docs: addressing deny-only gator flag nits

.github/workflows/release.yaml
(cherry picked from commit 0d9dbbf7d000b6bc72a58a5ec12417446325772c)
Fixes #
=> fix: adding a comment to clean up disk space in runner (CP: 3877)

test/export/fake-subscriber/Dockerfile
=> fix: updating golang version in subscriber dockerfile

cmd/gator/test/gatortest_test.go, pkg/controller/config/config_controller_test.go, pkg/controller/constraint/constraint_controller.go, pkg/controller/constraint/constraint_controller_test.go, pkg/controller/externaldata/externaldata_controller_test.go, pkg/controller/mutators/core/controller_test.go, pkg/drivers/k8scel/transform/make_vap_objects.go, pkg/drivers/k8scel/transform/make_vap_objects_test.go, pkg/readiness/ready_tracker_test.go, pkg/watch/manager_integration_test.go, test/testutils/manager.go, website/docs/validating-admission-policy.md, website/versioned_docs/version-v3.17.x/validating-admission-policy.md, website/versioned_docs/version-v3.18.x/validating-admission-policy.md, website/versioned_docs/version-v3.19.x/validating-admission-policy.md
=> feat: mapping dryrun to audit in vapb

.github/workflows/test-gator.yaml, .github/workflows/workflow.yaml, Makefile, crd.Dockerfile, test/externaldata/dummy-provider/Dockerfile, test/image/Dockerfile
=> ci: bumping k8s version in testing and crd.Dockerfile

pkg/webhook/policy.go, pkg/webhook/policy_test.go
(cherry picked from commit 8d048b0655b0a0e7f31e172bc4aaf27b685e0714)
Fixes #
=> fix: error on deleting GK resources when delete operation is enabled CP(#3921) 

.github/workflows/test-gator.yaml, .github/workflows/workflow.yaml, Makefile, crd.Dockerfile, test/externaldata/dummy-provider/Dockerfile, test/image/Dockerfile
(cherry picked from commit e331f36b93e6f4762684fd637f29b8ac1ba84c60)
Fixes #
=> ci: bumping k8s version in testing and crd.Dockerfile CP(#3925)

website/docs/constrainttemplates.md, website/docs/validating-admission-policy.md, website/versioned_docs/version-v3.18.x/constrainttemplates.md, website/versioned_docs/version-v3.18.x/validating-admission-policy.md, website/versioned_docs/version-v3.19.x/constrainttemplates.md, website/versioned_docs/version-v3.19.x/validating-admission-policy.md
=> docs: adding available variables and updating faq

Dockerfile, build/tooling/Dockerfile, gator.Dockerfile, test/export/fake-reader/Dockerfile
Fixes CVEs - https://github.com/open-policy-agent/gatekeeper/actions/runs/15687050533/job/44192770870?pr=3999#step:9:36
Fixes #
=> chore: bumping go in dockerfiles

pkg/export/disk/disk.go, pkg/export/disk/disk_test.go, test/export/fake-reader/export_connection.yaml, website/docs/export.md
=> chore: exposing TTL in disk driver
